import { existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync } from 'fs';
import { join } from 'path';
import { log } from '../utils/logger.js';

const START_MARKER = '# cdd-kit-code-map-block-start';
const END_MARKER   = '# cdd-kit-code-map-block-end';

const CODE_MAP_BLOCK = `${START_MARKER}
# Auto-regenerates .cdd/code-map.yml when source files are staged.
# Generated by: cdd-kit init --hooks (re-run to update).
# Extension list mirrors src/code-map/config.ts BUILTIN_INCLUDE.
staged_src=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(py|js|jsx|mjs|cjs|ts|tsx|vue)$' || true)
if [ -n "$staged_src" ]; then
  if cdd-kit code-map --check >/dev/null 2>&1; then
    : # already up to date
  else
    echo "[cdd-kit] regenerating .cdd/code-map.yml"
    if ! cdd-kit code-map; then
      echo "[cdd-kit] code-map generation failed — commit rejected."
      exit 1
    fi
    git add .cdd/code-map.yml
  fi
fi
${END_MARKER}`;

export async function installCodeMapHook(cwd: string): Promise<void> {
  const gitDir = join(cwd, '.git');

  if (!existsSync(gitDir)) {
    log.warn('not a git repository (no .git/ found); skipping code-map hook installation');
    return;
  }

  const hooksDir = join(gitDir, 'hooks');
  mkdirSync(hooksDir, { recursive: true });

  const dest = join(hooksDir, 'pre-commit');

  let final: string;

  if (!existsSync(dest)) {
    // No existing hook — create fresh
    final = `#!/bin/sh\nset -e\n\n${CODE_MAP_BLOCK}\n`;
  } else {
    const existing = readFileSync(dest, 'utf8');
    const startIdx = existing.indexOf(START_MARKER);
    const endIdx = existing.indexOf(END_MARKER);

    if (startIdx >= 0 && endIdx > startIdx) {
      // Existing code-map block — replace it in place (idempotent)
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + END_MARKER.length);
      final = before + CODE_MAP_BLOCK + after;
    } else {
      // No code-map block yet — append after existing content
      // Preserve the existing content exactly; add block at end
      const trimmed = existing.trimEnd();
      final = trimmed + '\n\n' + CODE_MAP_BLOCK + '\n';
    }
  }

  writeFileSync(dest, final, 'utf8');
  try {
    chmodSync(dest, 0o755);
  } catch { /* ignore on Windows */ }

  // Drop a marker so `cdd-kit refresh` knows to re-install on next run.
  // Marker path is intentionally inside .cdd/ so it travels with the repo.
  try {
    const cddDir = join(cwd, '.cdd');
    mkdirSync(cddDir, { recursive: true });
    writeFileSync(join(cddDir, '.hooks-installed'), `installed: ${new Date().toISOString()}\n`, 'utf8');
  } catch { /* non-fatal */ }

  log.ok(`code-map pre-commit hook installed at ${dest}`);
}
