import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { basename, join, relative } from 'path';
import { log } from '../utils/logger.js';

const DEFAULT_FORBIDDEN = [
  '.claude',
  '.git',
  'node_modules',
  'dist',
  'build',
  'assets',
  'specs/archive',
  'specs/changes',
];

function stripGlobSuffix(pattern: string): string {
  return pattern.replace(/\/\*\*$/, '').replace(/\/\*$/, '');
}

function getForbiddenPaths(cwd: string): string[] {
  const forbidden = new Set(DEFAULT_FORBIDDEN);
  const policyPath = join(cwd, '.cdd', 'context-policy.json');

  try {
    if (existsSync(policyPath)) {
      const policy = JSON.parse(readFileSync(policyPath, 'utf8')) as { forbiddenPaths?: string[] };
      for (const pattern of policy.forbiddenPaths ?? []) {
        forbidden.add(stripGlobSuffix(pattern));
      }
    }
  } catch {
    log.warn('Could not parse .cdd/context-policy.json; using default context-scan excludes.');
  }

  return [...forbidden];
}

function isForbidden(relPath: string, forbidden: string[]): boolean {
  const normalized = relPath.replace(/\\/g, '/');
  return forbidden.some(pattern => normalized === pattern || normalized.startsWith(`${pattern}/`));
}

function buildTree(dir: string, cwd: string, forbidden: string[], prefix = '', depth = 0): string {
  const entries = readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => {
      if (a.isDirectory() === b.isDirectory()) return a.name.localeCompare(b.name);
      return a.isDirectory() ? -1 : 1;
    });

  let output = '';
  const visible = entries.filter(entry => {
    const relPath = relative(cwd, join(dir, entry.name));
    return !isForbidden(relPath, forbidden);
  });

  visible.forEach((entry, index) => {
    const fullPath = join(dir, entry.name);
    const isLast = index === visible.length - 1;
    const connector = isLast ? '\\-- ' : '|-- ';
    output += `${prefix}${connector}${entry.name}${entry.isDirectory() ? '/' : ''}\n`;

    if (entry.isDirectory()) {
      if (depth >= 3) {
        output += `${prefix}${isLast ? '    ' : '|   '}\\-- ... (max depth)\n`;
      } else {
        output += buildTree(fullPath, cwd, forbidden, prefix + (isLast ? '    ' : '|   '), depth + 1);
      }
    }
  });

  return output;
}

function parseContractMetadata(content: string): { summary?: string; metadata: Record<string, string> } {
  const metadata: Record<string, string> = {};
  let summary: string | undefined;

  const cddMatch = content.match(/<!--\s*cdd:([\s\S]*?)-->/);
  const yamlMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const block = cddMatch?.[1] ?? yamlMatch?.[1];

  if (block) {
    for (const line of block.split(/\r?\n/)) {
      const colon = line.indexOf(':');
      if (colon === -1) continue;
      const key = line.slice(0, colon).trim();
      const value = line.slice(colon + 1).trim();
      if (!key || !value) continue;
      if (key === 'summary') summary = value;
      else metadata[key] = value;
    }
  }

  if (!summary) {
    const summaryMatch = content.match(/#+\s*Summary\s*\r?\n+([^#\r\n][^\r\n]*)/i);
    summary = summaryMatch?.[1]?.trim();
  }

  return { summary, metadata };
}

function findContractFiles(dir: string, found: string[] = []): string[] {
  if (!existsSync(dir)) return found;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) findContractFiles(fullPath, found);
    else if (entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'INDEX.md') found.push(fullPath);
  }
  return found;
}

export async function contextScan(): Promise<void> {
  const cwd = process.cwd();
  const specsContextDir = join(cwd, 'specs', 'context');
  mkdirSync(specsContextDir, { recursive: true });

  const forbidden = getForbiddenPaths(cwd);
  const tree = buildTree(cwd, cwd, forbidden);
  writeFileSync(
    join(specsContextDir, 'project-map.md'),
    `# Project Map\n\nGenerated by \`cdd-kit context-scan\`.\n\n\`\`\`\n${basename(cwd)}/\n${tree}\`\`\`\n`,
    'utf8',
  );
  log.ok('Created specs/context/project-map.md');

  let contractIndex = '# Contracts Index\n\nGenerated by `cdd-kit context-scan` from deterministic metadata.\n\n';
  let missingSummary = 0;
  for (const file of findContractFiles(join(cwd, 'contracts'))) {
    const relPath = relative(cwd, file).replace(/\\/g, '/');
    const { summary, metadata } = parseContractMetadata(readFileSync(file, 'utf8'));
    contractIndex += `## ${relPath}\n`;
    contractIndex += `- path: \`${relPath}\`\n`;
    for (const [key, value] of Object.entries(metadata)) {
      contractIndex += `- ${key}: ${value}\n`;
    }
    if (summary) {
      contractIndex += `- summary: ${summary}\n\n`;
    } else {
      contractIndex += '- summary: MISSING - add YAML frontmatter `summary:` or `<!-- cdd: summary: ... -->`.\n\n';
      missingSummary += 1;
    }
  }

  writeFileSync(join(specsContextDir, 'contracts-index.md'), contractIndex, 'utf8');
  if (missingSummary > 0) {
    log.warn(`Created specs/context/contracts-index.md with ${missingSummary} missing summary warning(s).`);
  } else {
    log.ok('Created specs/context/contracts-index.md');
  }
}
