import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { spawnSync } from 'child_process';
import { join } from 'path';
import { log } from '../utils/logger.js';
import { inferProvider, validateProviderOption, type ProviderOption } from '../utils/provider.js';
import { detectStack } from '../utils/stack-detect.js';
import { ASSET } from '../utils/paths.js';
import { readAssetManifest } from '../utils/asset-manifest.js';
import { sha256OfFileNormalized } from '../utils/digest.js';
import { checkCodeMapFreshness } from '../code-map/freshness.js';
import { collectAgentViolations } from './lint-agents.js';
import { detectChokepoints } from './chokepoints.js';
import { staleMetadataReport, writeMetadataFiles } from './metadata.js';
import { stripFrontmatter, parseEndpoints, parseContractSchemas, detectSchemaCellNearMiss, SCHEMA_NAME_RE, DEFAULT_CONTRACT_PATH, projectApplicability } from '../contracts/parser.js';

export interface DoctorOptions {
  strict?: boolean;
  provider?: ProviderOption;
  json?: boolean;
  fix?: boolean;
  /**
   * Render a plain-language ✅/⚠️ summary instead of the full technical finding
   * list. For non-engineers who need "is this healthy or not, and what next?"
   * rather than 15 lines of digests and chokepoint detail.
   */
  simple?: boolean;
}

interface Finding {
  level: 'error' | 'warning' | 'ok';
  message: string;
}

interface DoctorReport {
  provider: string;
  strict: boolean;
  findings: Finding[];
  errors: number;
  warnings: number;
  ok: boolean;
}

function fileExists(cwd: string, relPath: string): boolean {
  return existsSync(join(cwd, relPath));
}

// Doctor recomputes the same inputs-digest that context-scan stamped into the
// index frontmatter; both the digest algorithm and the input-file selection are
// shared modules (P1-17) so the writer and the checker cannot drift.
import { inputsDigest } from '../utils/digest.js';
import { findContractFiles, projectMapInputs } from '../utils/context-inputs.js';

function readContextIndexMetadata(filePath: string): { inputsDigest?: string; missingSummary?: number } {
  if (!existsSync(filePath)) return {};
  const text = readFileSync(filePath, 'utf8');
  const out: { inputsDigest?: string; missingSummary?: number } = {};
  const digestMatch = text.match(/^inputs-digest:\s*([a-f0-9]+)/m);
  if (digestMatch) out.inputsDigest = digestMatch[1];
  const missingMatch = text.match(/^missing-summary-count:\s*(\d+)/m);
  if (missingMatch) out.missingSummary = Number(missingMatch[1]);
  return out;
}

function checkContextFreshness(cwd: string): Finding[] {
  const findings: Finding[] = [];
  const projectMap = join(cwd, 'specs', 'context', 'project-map.md');
  const contractsIndex = join(cwd, 'specs', 'context', 'contracts-index.md');
  const contractFiles = findContractFiles(join(cwd, 'contracts'));

  if (!existsSync(projectMap) || !existsSync(contractsIndex)) {
    findings.push({
      level: 'warning',
      message: 'specs/context indexes are missing; run cdd-kit context-scan before classification',
    });
    return findings;
  }

  // Hash-based freshness: compare inputs-digest in the index frontmatter against
  // the live hash of the actual input files. mtime is unreliable across git clone.
  const projectMapMeta = readContextIndexMetadata(projectMap);
  const contractsIndexMeta = readContextIndexMetadata(contractsIndex);

  const projectInputDigest = inputsDigest(projectMapInputs(cwd), cwd);
  if (projectMapMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (projectInputDigest && projectMapMeta.inputsDigest !== projectInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md inputs changed (.cdd/context-policy.json); re-run cdd-kit context-scan',
    });
  }

  const contractsInputDigest = inputsDigest(contractFiles, cwd);
  if (contractsIndexMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (contractsInputDigest && contractsIndexMeta.inputsDigest !== contractsInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md inputs changed (contracts/*); re-run cdd-kit context-scan',
    });
  }

  if (contractsIndexMeta.missingSummary !== undefined && contractsIndexMeta.missingSummary > 0) {
    findings.push({
      level: 'warning',
      message: `contracts-index reports ${contractsIndexMeta.missingSummary} contract(s) without deterministic summary metadata`,
    });
  }

  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'context indexes are present and fresh' });
  }
  return findings;
}

function readAgentModel(path: string): string | null {
  try {
    const text = readFileSync(path, 'utf8');
    const m = text.match(/^model:\s*(\S+)/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

function checkModelPolicyDrift(cwd: string): Finding[] {
  const policyPath = join(cwd, '.cdd', 'model-policy.json');
  if (!existsSync(policyPath)) return [];

  let policy: { roles?: Record<string, string> };
  try {
    policy = JSON.parse(readFileSync(policyPath, 'utf8'));
  } catch {
    return [{ level: 'warning', message: '.cdd/model-policy.json is not valid JSON' }];
  }

  const roles = policy.roles ?? {};
  if (Object.keys(roles).length === 0) {
    return [{
      level: 'warning',
      message: '.cdd/model-policy.json has no role bindings; run cdd-kit upgrade to install defaults',
    }];
  }

  // Walk both global (~/.claude/agents) and project (.claude/agents) if present.
  const candidateDirs = [
    join(cwd, '.claude', 'agents'),
    process.env.HOME ? join(process.env.HOME, '.claude', 'agents') : '',
    process.env.USERPROFILE ? join(process.env.USERPROFILE, '.claude', 'agents') : '',
  ].filter(p => p && existsSync(p));

  if (candidateDirs.length === 0) return [];

  const findings: Finding[] = [];
  for (const [role, expected] of Object.entries(roles)) {
    let foundAny = false;
    for (const dir of candidateDirs) {
      const path = join(dir, `${role}.md`);
      if (!existsSync(path)) continue;
      foundAny = true;
      const actual = readAgentModel(path);
      if (actual && actual !== expected) {
        findings.push({
          level: 'warning',
          message: `model-policy drift: ${role} expected ${expected}, agent prompt uses ${actual} (${path})`,
        });
      }
    }
    if (!foundAny) {
      // Not installed locally; not an error — global install may still be missing this role.
    }
  }
  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'model-policy roles match installed agent prompts' });
  }
  return findings;
}

/**
 * Maps an installed repo-relative path (as recorded in `.cdd/asset-manifest.json`,
 * ADR 0010 §6 / design.md Q3) back to the packaged asset that would currently
 * produce it, so drift can be checked against the RUNNING cdd-kit package, not
 * just the manifest's own recorded digest. Order does not matter: every prefix
 * here is disjoint.
 */
function packagedPathFor(relpath: string): string | null {
  const mappings: Array<{ prefix: string; assetDir: string }> = [
    { prefix: 'specs/templates/', assetDir: ASSET.specsTemplates },
    { prefix: 'tests/templates/', assetDir: ASSET.testsTemplates },
    { prefix: 'tests/contract/', assetDir: ASSET.contractHarness },
    { prefix: 'ci-templates/', assetDir: join(ASSET.ci, '..', 'ci-templates') },
    { prefix: 'ci/', assetDir: ASSET.ci },
    { prefix: '.github/workflows/', assetDir: ASSET.githubWorkflows },
    { prefix: '.claude/hooks/', assetDir: ASSET.hooks },
    { prefix: '.cdd/', assetDir: ASSET.cddConfig },
    { prefix: 'contracts/', assetDir: ASSET.contracts },
  ];
  for (const { prefix, assetDir } of mappings) {
    if (relpath.startsWith(prefix)) return join(assetDir, relpath.slice(prefix.length));
  }
  return null;
}

/**
 * ADR 0010 §6 (AC-8): compare every asset stamped in `.cdd/asset-manifest.json`
 * against (1) the file actually on disk -- post-install drift, a hand-edited or
 * partially-restored copy -- and (2) the asset currently packaged with this
 * cdd-kit install -- a stale install that predates a package upgrade, or one
 * `refresh`/`upgrade` never got around to picking up. Both are best-effort,
 * read-only, and advisory: a repo that never ran refresh/upgrade/
 * install-agent-hooks carries no manifest and reports nothing here.
 */
function checkAssetManifestDrift(cwd: string): Finding[] {
  const manifest = readAssetManifest(cwd);
  const relpaths = Object.keys(manifest);
  if (relpaths.length === 0) return [];

  const findings: Finding[] = [];
  for (const rel of relpaths) {
    const entry = manifest[rel];
    const installedAbs = join(cwd, rel);
    if (!existsSync(installedAbs)) {
      findings.push({
        level: 'warning',
        message: `asset-manifest: ${rel} is missing (recorded in .cdd/asset-manifest.json but not on disk); run \`cdd-kit refresh\` or \`cdd-kit upgrade --yes\``,
      });
      continue;
    }

    const installedDigest = sha256OfFileNormalized(installedAbs);
    if (installedDigest !== entry.digest) {
      findings.push({
        level: 'warning',
        message: `asset-manifest: ${rel} was modified after install (digest differs from its recorded v${entry.version} stamp) — partial or hand-edited copy; run \`cdd-kit refresh\` to restore`,
      });
      continue; // already flagged as drifted; the packaged comparison below would be redundant
    }

    const packagedAbs = packagedPathFor(rel);
    if (packagedAbs && existsSync(packagedAbs)) {
      const packagedDigest = sha256OfFileNormalized(packagedAbs);
      if (packagedDigest !== installedDigest) {
        findings.push({
          level: 'warning',
          message: `asset-manifest: ${rel} differs from the currently packaged cdd-kit asset (installed at v${entry.version} is stale) — run \`cdd-kit refresh\` to pick up the current package version`,
        });
      }
    }
  }
  return findings;
}

function checkAgentLint(cwd: string): Finding[] {
  const agentsDir = join(cwd, '.claude', 'agents');
  if (!existsSync(agentsDir)) return [];

  // Delegate to the single source of truth for agent-prompt shape rules so
  // doctor and `cdd-kit lint-agents` can never report different verdicts.
  const violations = collectAgentViolations(cwd);
  if (violations === null) {
    // The directory exists (checked above) but readdir failed -- a real
    // permission/IO error, not "no agents configured". Surface it instead of
    // silently reporting a clean pass.
    return [{
      level: 'warning',
      message: `lint-agents: could not read ${join('.claude', 'agents')} -- agent prompts were not scanned`,
    }];
  }

  const findings: Finding[] = violations.map(v => ({
    level: 'warning',
    message: `lint-agents: ${v.file}: [Rule ${v.rule}] ${v.message}`,
  }));

  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'lint-agents: all agent prompts pass shape checks' });
  }
  return findings;
}

function checkCodeMap(cwd: string): Finding[] {
  const findings: Finding[] = [];
  const mapPath = join(cwd, '.cdd', 'code-map.yml');
  if (!existsSync(mapPath)) {
    const probe = checkCodeMapFreshness(cwd);
    if (probe.status === 'config-error') {
      findings.push({ level: 'warning', message: `.cdd/code-map-config.yml is invalid: ${probe.configError}` });
    } else if (probe.status === 'missing-with-sources') {
      findings.push({ level: 'warning', message: '.cdd/code-map.yml is missing; run `cdd-kit code-map`' });
    }
    return findings;
  }
  const probe = checkCodeMapFreshness(cwd);
  if (probe.status === 'config-error') {
    findings.push({ level: 'warning', message: `.cdd/code-map-config.yml is invalid: ${probe.configError}` });
    return findings;
  }
  if (probe.status === 'stale') {
    const top = probe.staleFiles.slice(0, 3).join(', ');
    const more = probe.staleCount > 3 ? ` (+${probe.staleCount - 3} more)` : '';
    findings.push({ level: 'warning', message: `code-map stale: ${top}${more}; run \`cdd-kit code-map\`` });
  }
  // Compression metric from header
  const text = readFileSync(mapPath, 'utf8');
  const m = text.match(/^# files: (\d+), src-lines: (\d+), map-lines: (\d+), compression: ([\d.]+)x/m);
  if (m) {
    findings.push({ level: 'ok', message: `code-map: ${m[1]} files, ${m[4]}x compression` });
  } else {
    findings.push({ level: 'warning', message: '.cdd/code-map.yml has no metadata header (regenerate with cdd-kit 2.0.5+)' });
  }
  return findings;
}

/**
 * API conformance is *applicable* when there is an API contract AND real source
 * code to drift from it. The most-needy users (non-engineers) are the least
 * likely to flip `enabled: true` themselves, so when it applies and is off we
 * route them to `cdd-kit doctor --fix`, which turns it on (P1-5). Detection
 * stays read-only; enabling is never silent.
 */
function conformanceApplicable(cwd: string): boolean {
  if (!existsSync(join(cwd, 'contracts', 'api', 'api-contract.md'))) return false;
  try {
    return detectStack(cwd).primary !== 'unknown';
  } catch {
    return false;
  }
}

function checkApiConformance(cwd: string): Finding[] {
  // For autonomous agent delivery, applicable-but-off conformance is a degraded
  // safety net, not a clean bill of health. Keep non-applicable repos
  // informational, but warn when a real codebase with an API contract has drift
  // detection available and disabled.
  const hasContract = existsSync(join(cwd, 'contracts', 'api', 'api-contract.md'));
  if (!hasContract) return [];
  const applicable = conformanceApplicable(cwd);
  const configPath = join(cwd, '.cdd', 'conformance.json');
  if (!existsSync(configPath)) {
    return [{
      level: applicable ? 'warning' : 'ok',
      message: applicable
        ? 'API conformance: available but not configured — run `cdd-kit doctor --fix` to enable code-vs-contract drift checks'
        : 'API conformance: not configured (add .cdd/conformance.json with "enabled": true to catch frontend/backend drift against the contract)',
    }];
  }
  try {
    const cfg = JSON.parse(readFileSync(configPath, 'utf8'));
    if (cfg.enabled) {
      return [{
        level: 'ok',
        message: 'API conformance: enabled (cdd-kit validate --contracts checks code against the API contract)',
      }];
    }
    return [{
      level: applicable ? 'warning' : 'ok',
      message: applicable
        ? 'API conformance: OFF — run `cdd-kit doctor --fix` to turn on code-vs-contract drift checks (or set "enabled": true in .cdd/conformance.json)'
        : 'API conformance: present but disabled (set "enabled": true in .cdd/conformance.json to enforce code-vs-contract checks)',
    }];
  } catch {
    return [{ level: 'warning', message: '.cdd/conformance.json is not valid JSON' }];
  }
}

/**
 * Response-shape coverage (ADR 0007). The body-level gate is opt-in by adoption
 * (a tests/contract/response-samples.json manifest), so without a nudge it stays
 * dormant — the prose-governance trap. This makes the gap a mechanical signal an
 * agent (or human) sees on `doctor`/`setup`: how many endpoints carry a typed
 * response schema vs prose, and whether the sample harness exists to enforce
 * them. Read-only and never an error — it drives migration, it does not block.
 */
function checkResponseShapeCoverage(cwd: string): Finding[] {
  const contractPath = join(cwd, DEFAULT_CONTRACT_PATH);
  if (!existsSync(contractPath)) return [];
  let endpoints: ReturnType<typeof parseEndpoints>;
  let schemas: Record<string, unknown>;
  try {
    const { body } = stripFrontmatter(readFileSync(contractPath, 'utf8'));
    endpoints = parseEndpoints(body);
    schemas = parseContractSchemas(body).schemas;
  } catch {
    return []; // a malformed contract is the structural validators' concern
  }
  if (endpoints.length === 0) return [];

  // An endpoint's response body is "typed" (machine-enforceable) when its
  // response cell resolves to a defined schema — a bare name or Name[].
  const resolves = (cell: string): boolean => {
    const raw = cell.trim();
    if (!raw || raw === '-') return false;
    const name = raw.endsWith('[]') ? raw.slice(0, -2).trim() : raw;
    return SCHEMA_NAME_RE.test(name) && name in schemas;
  };
  const typed = endpoints.filter(e => resolves(e.response)).length;
  const applicable = (() => { try { return detectStack(cwd).primary !== 'unknown'; } catch { return false; } })();
  const hasManifest = existsSync(join(cwd, 'tests', 'contract', 'response-samples.json'));

  const findings: Finding[] = [];

  // Near-miss: a response cell names a DEFINED schema but in a non-bare form
  // (`→ AckResponse`, `AckResponse (success)`), so cdd-kit treats it as prose and
  // emits no $ref — the body is silently unenforced. This is a high-signal typo,
  // not incremental adoption, so surface it as its own warning (trips --strict)
  // rather than letting it hide inside the aggregate "0 typed" count.
  const definedNames = new Set(Object.keys(schemas));
  const nearMisses = endpoints
    .map(e => ({ e, nm: detectSchemaCellNearMiss(e.response, definedNames) }))
    .filter((x): x is { e: typeof x.e; nm: NonNullable<typeof x.nm> } => x.nm !== null)
    .map(({ e, nm }) => `${e.method.toUpperCase()} ${e.path} response cell "${e.response.trim()}" → use bare \`${nm.suggestion}\``);
  if (nearMisses.length > 0) {
    const head = nearMisses.slice(0, 3).join('; ');
    const more = nearMisses.length > 3 ? ` (+${nearMisses.length - 3} more)` : '';
    findings.push({
      level: 'warning',
      message: `Response-shape: ${nearMisses.length} response cell(s) name a defined schema in a non-bare form, so cdd-kit treats them as prose and the body is NOT enforced — ${head}${more}. Use the bare schema name (ADR 0007).`,
    });
  }

  if (typed === 0) {
    findings.push({
      level: applicable ? 'warning' : 'ok',
      message: applicable
        ? `Response-shape: ${endpoints.length} endpoint(s), 0 with a typed response schema — response bodies are prose, so the data-shape gate enforces nothing. Migrate high-value endpoints to a typed \`## Schemas\` entry + add tests/contract/response-samples.json (ADR 0007).`
        : 'Response-shape: response bodies are prose; declare typed `## Schemas` entries to enable the data-shape gate (ADR 0007).',
    });
  } else if (!hasManifest) {
    findings.push({
      level: 'warning',
      message: `Response-shape: ${typed} endpoint(s) declare a typed response schema but tests/contract/response-samples.json is absent — copy tests/contract/response-samples.example.json and capture samples so the gate enforces them (ADR 0007).`,
    });
  } else {
    findings.push({
      level: 'ok',
      message: `Response-shape: ${typed} typed response endpoint(s) with a sample manifest — the data-shape gate enforces response bodies (cdd-kit validate --contracts).`,
    });
  }
  return findings;
}

/** Same REQUIRED contract-family surfaces validate_contracts.py enforces (ADR 0011). */
const APPLICABILITY_SURFACES: Array<{ path: string; label: string }> = [
  { path: 'contracts/api/api-contract.md', label: 'API' },
  { path: 'contracts/css/css-contract.md', label: 'CSS/UI' },
  { path: 'contracts/env/env-contract.md', label: 'Env' },
  { path: 'contracts/data/data-shape-contract.md', label: 'Data shape' },
  { path: 'contracts/business/business-rules.md', label: 'Business' },
  { path: 'contracts/ci/ci-gate-contract.md', label: 'CI/CD' },
];

const APPLICABILITY_PLACEHOLDER_THRESHOLD = 470;

/** Mirrors validate_contracts.py's `meaningful_chars` (markdown headings,
 * blank lines, table borders, and comment-opener lines stripped). Kept as its
 * own copy (not shared with the Python metric) since it feeds an advisory
 * display-only finding, not a pass/fail decision. */
function meaningfulChars(text: string): string {
  const filtered: string[] = [];
  for (const rawLine of text.split('\n')) {
    const s = rawLine.trim();
    if (!s) continue;
    if (s.startsWith('#')) continue;
    if (/^[|\s\-:]+$/.test(s)) continue;
    if (s.startsWith('<!--')) continue;
    filtered.push(s);
  }
  return filtered.join('');
}

/**
 * Read-only display of the applicability marker (ADR 0011): lists every
 * contract marked `applicability: not-applicable` with its recorded reason
 * (AC-4), and warns when a marked contract's BODY now looks filled — the mark
 * may be stale (AC-7, drift). This NEVER makes a pass/fail decision;
 * `applicability.py` (the Python validators) is the sole authority (design.md
 * decision 2) — this is display only.
 */
function checkContractApplicability(cwd: string): Finding[] {
  const findings: Finding[] = [];
  for (const { path: relPath, label } of APPLICABILITY_SURFACES) {
    const full = join(cwd, relPath);
    if (!existsSync(full)) continue;
    let frontmatter: Record<string, string>;
    let body: string;
    try {
      const raw = readFileSync(full, 'utf8');
      const parsed = stripFrontmatter(raw);
      frontmatter = parsed.frontmatter;
      body = parsed.body;
    } catch {
      continue; // a malformed/unreadable contract is the structural validators' concern
    }
    const projection = projectApplicability(frontmatter);
    if (projection.status !== 'not-applicable') continue;

    findings.push({
      level: 'ok',
      message: `${label} contract (${relPath}) marked applicability: not-applicable — ${projection.reason}`,
    });

    if (meaningfulChars(body).length >= APPLICABILITY_PLACEHOLDER_THRESHOLD) {
      findings.push({
        level: 'warning',
        message: `${label} contract (${relPath}) is marked applicability: not-applicable but its body now looks filled — the mark may be stale; reconsider it (ADR 0011).`,
      });
    }
  }
  return findings;
}

function checkMcpRegistration(cwd: string, provider: string): Finding[] {
  // Observability for the silent-degradation failure mode: if the cdd-kit MCP
  // server is not registered, agents never see the graph/index tools and
  // silently fall back to `Read`, defeating the `--with-source` exploration path
  // and making the whole kit feel "slow" for no visible reason.
  //
  // Severity is tiered on *certainty* (P1-1): when `claude` is present and
  // positively reports the server missing on a real cdd-kit project, that is a
  // `warning` (trips `--strict`) — we know agents are degraded. When we cannot
  // verify (no `claude` CLI, `mcp list` errored), it stays informational (`ok`)
  // so environments that don't use Claude Code are never penalised.
  if (provider !== 'claude' && provider !== 'both') return [];

  // Only nudge actual cdd-kit projects (inferProvider defaults to 'claude' even
  // for unrelated repos). `.cdd/` is the definitive marker that init created.
  if (!existsSync(join(cwd, '.cdd'))) return [];

  const bin = process.env.CDD_CLAUDE_BIN || 'claude';
  let result;
  try {
    // Mirror the CDD_CODEGRAPH_BIN convention: a `.js` override is run via node
    // so tests can stub the Claude CLI portably.
    // Short timeout: doctor must stay fast and must never hang on an external
    // CLI. If `claude mcp list` is slow, we report "could not verify" rather
    // than block.
    result = bin.toLowerCase().endsWith('.js')
      ? spawnSync(process.execPath, [bin, 'mcp', 'list'], { encoding: 'utf8', timeout: 3000 })
      : spawnSync(bin, ['mcp', 'list'], { encoding: 'utf8', timeout: 3000 });
  } catch {
    result = { error: new Error('spawn failed') } as ReturnType<typeof spawnSync>;
  }

  if (result.error || typeof result.status !== 'number') {
    return [{
      level: 'ok',
      message: 'MCP: could not run `claude mcp list` (Claude Code CLI not found); skip if you do not use Claude Code',
    }];
  }
  if (result.status !== 0) {
    return [{
      level: 'ok',
      message: `MCP: \`claude mcp list\` exited ${result.status}; cannot verify cdd-kit registration`,
    }];
  }

  const output = `${result.stdout ?? ''}${result.stderr ?? ''}`;
  if (/\bcdd-kit\b/.test(output)) {
    return [{ level: 'ok', message: 'MCP: cdd-kit server is registered with Claude Code' }];
  }
  // Positive confirmation that the server is missing on a Claude project: this
  // is the silent-slow-mode case, so warn (and fail --strict) rather than tuck
  // it into informational output the user never reads.
  return [{
    level: 'warning',
    message: 'MCP: cdd-kit not registered — agents will fall back to the slower Read path instead of the graph/index tools; run `claude mcp add --scope user cdd-kit -- cdd-kit mcp` (or `cdd-kit setup`)',
  }];
}

/**
 * Derived-index freshness (P2-1). Flags changes whose generated change.yml /
 * trace.yml have drifted from their source artifacts. Warning-level so it trips
 * `--strict` and is auto-fixable, but only for changes that ALREADY HAVE a
 * generated index — doctor never nags about a derived index a change chose not
 * to generate (use `cdd-kit metadata <id>` to opt in).
 */
function checkChangeMetadata(stale: { id: string; stale: string[] }[]): Finding[] {
  return stale.map(s => ({
    level: 'warning' as const,
    message: `change ${s.id}: metadata is stale (${s.stale.join(', ')}); run \`cdd-kit metadata ${s.id}\` or \`cdd-kit doctor --fix\``,
  }));
}

function checkChokepoints(cwd: string): Finding[] {
  // Enforcement-liveness dashboard. In an autonomous-agent workflow, dormant
  // chokepoints mean the repo carries the machinery but does not actually steer
  // agents away from high-risk defaults, so surface them as warnings.
  if (!existsSync(join(cwd, '.cdd'))) return [];
  return detectChokepoints(cwd).map(c => ({
    level: c.live ? 'ok' as const : 'warning' as const,
    message: c.live
      ? `chokepoint ${c.name}: live — ${c.detail}`
      : `chokepoint ${c.name}: ${c.detail}`,
  }));
}

async function buildDoctorReport(cwd: string, opts: DoctorOptions): Promise<DoctorReport> {
  const requestedProvider = opts.provider ?? 'auto';
  if (!validateProviderOption(requestedProvider)) {
    log.error(`Invalid provider: ${requestedProvider}. Use auto, claude, codex, or both.`);
    process.exit(1);
  }

  const strict = opts.strict ?? false;
  const provider = inferProvider(cwd, requestedProvider);
  const findings: Finding[] = [];

  for (const relPath of ['contracts', 'specs/templates', '.cdd/context-policy.json', '.cdd/model-policy.json', '.cdd/policy.yml']) {
    findings.push(fileExists(cwd, relPath)
      ? { level: 'ok', message: `${relPath} exists` }
      : { level: 'warning', message: `${relPath} is missing; run cdd-kit upgrade --yes` });
  }

  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'CLAUDE.md')) {
    findings.push({ level: 'warning', message: 'CLAUDE.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'AGENTS.md')) {
    findings.push({ level: 'warning', message: 'AGENTS.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'codex' || provider === 'both') && !fileExists(cwd, 'AGENTS.md')) {
    findings.push({ level: 'warning', message: 'AGENTS.md is missing for Codex provider; run cdd-kit upgrade --provider codex --yes' });
  }

  findings.push(...checkContextFreshness(cwd));
  findings.push(...checkModelPolicyDrift(cwd));
  findings.push(...checkAgentLint(cwd));
  findings.push(...checkCodeMap(cwd));
  findings.push(...checkApiConformance(cwd));
  findings.push(...checkResponseShapeCoverage(cwd));
  findings.push(...checkContractApplicability(cwd));
  findings.push(...checkMcpRegistration(cwd, provider));
  findings.push(...checkChangeMetadata(staleMetadataReport(cwd)));
  findings.push(...checkChokepoints(cwd));
  findings.push(...checkAssetManifestDrift(cwd));

  const errors = findings.filter(finding => finding.level === 'error').length;
  const warnings = findings.filter(finding => finding.level === 'warning').length;
  return {
    provider,
    strict,
    findings,
    errors,
    warnings,
    ok: errors === 0 && (!strict || warnings === 0),
  };
}

/**
 * Turn on API conformance when it applies (contract + real source) and is
 * currently off. This is the actionable half of P1-5: plain `doctor` only
 * *surfaces* that drift detection is off (informational), and `--fix` flips the
 * switch — the on-ramp the most-needy users won't take themselves. Reversible
 * (set "enabled": false to undo) and gated on applicability so it never enables
 * conformance on a contract-only repo with nothing to check.
 */
function enableConformanceIfApplicable(cwd: string): string | null {
  if (!conformanceApplicable(cwd)) return null;
  const configPath = join(cwd, '.cdd', 'conformance.json');
  let cfg: Record<string, unknown>;
  if (existsSync(configPath)) {
    try {
      cfg = JSON.parse(readFileSync(configPath, 'utf8'));
    } catch {
      return null; // malformed JSON is surfaced as its own warning; don't clobber it
    }
    if (cfg.enabled === true) return null; // already on
  } else {
    // No project config yet: seed from the shipped default so the user gets the
    // full, documented schema rather than a bare { enabled: true }.
    const assetPath = join(ASSET.cddConfig, 'conformance.json');
    try {
      cfg = JSON.parse(readFileSync(assetPath, 'utf8'));
    } catch {
      cfg = { enabled: false };
    }
  }
  cfg.enabled = true;
  try {
    mkdirSync(join(cwd, '.cdd'), { recursive: true });
    writeFileSync(configPath, JSON.stringify(cfg, null, 2) + '\n', 'utf8');
    return 'enabled API conformance in .cdd/conformance.json (code-vs-contract drift checks now run in `cdd-kit validate --contracts`)';
  } catch {
    return null;
  }
}

async function attemptAutoFixes(cwd: string, report: DoctorReport): Promise<{ fixed: string[]; remaining: Finding[] }> {
  const fixed: string[] = [];
  const remaining: Finding[] = [];

  // Conformance enablement is keyed off live repo state, not a warning-level
  // finding (the conformance check is informational), so handle it up front.
  const conformanceFix = enableConformanceIfApplicable(cwd);
  if (conformanceFix) fixed.push(conformanceFix);

  for (const finding of report.findings) {
    if (finding.level !== 'warning') {
      remaining.push(finding);
      continue;
    }

    // Stale or missing context indexes → run context-scan
    if (/specs\/context indexes are missing|inputs changed|older cdd-kit|older than/i.test(finding.message)) {
      try {
        const { contextScan } = await import('./context-scan.js');
        await contextScan();
        fixed.push(`ran context-scan to refresh specs/context/`);
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // code-map stale or missing → regenerate
    if (/code-map stale|code-map\.yml is missing/i.test(finding.message)) {
      try {
        const { codeMap } = await import('./code-map.js');
        await codeMap({ path: '.', out: '.cdd/code-map.yml', include: [], exclude: [], check: false, maxLines: 100000 });
        fixed.push('regenerated .cdd/code-map.yml');
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // derived metadata stale → regenerate change.yml / trace.yml (P2-1)
    const staleMeta = finding.message.match(/^change (\S+): metadata is stale/);
    if (staleMeta) {
      try {
        writeMetadataFiles(join(cwd, 'specs', 'changes', staleMeta[1]), cwd);
        fixed.push(`regenerated metadata for ${staleMeta[1]} (change.yml + trace.yml)`);
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // model-policy has no role bindings → write defaults
    // (check this BEFORE the generic .cdd/* upgrade-suggestion, because the
    //  no-role-bindings message also mentions "run cdd-kit upgrade")
    if (/model-policy\.json has no role bindings/i.test(finding.message)) {
      const policyPath = join(cwd, '.cdd', 'model-policy.json');
      try {
        let existing: Record<string, unknown> = {};
        try { existing = JSON.parse(readFileSync(policyPath, 'utf8')); } catch { /* ok */ }
        const merged = {
          ...existing,
          roles: {
            'change-classifier': 'opus',
            'spec-architect': 'opus',
            'qa-reviewer': 'opus',
            'contract-reviewer': 'sonnet',
            'test-strategist': 'sonnet',
            'bug-fix-engineer': 'sonnet',
            'backend-engineer': 'sonnet',
            'frontend-engineer': 'sonnet',
            'ci-cd-gatekeeper': 'sonnet',
            'e2e-resilience-engineer': 'sonnet',
            'monkey-test-engineer': 'sonnet',
            'stress-soak-engineer': 'sonnet',
            'ui-ux-reviewer': 'sonnet',
            'visual-reviewer': 'sonnet',
            'dependency-security-reviewer': 'sonnet',
            'spec-drift-auditor': 'opus',
            'repo-context-scanner': 'haiku',
          },
        };
        const { writeFileSync } = await import('fs');
        writeFileSync(policyPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
        fixed.push(`populated .cdd/model-policy.json with default role bindings`);
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // .cdd/* missing → suggest upgrade (don't run upgrade automatically;
    // it can write provider-specific files the user might not want)
    if (/\.cdd\/.*is missing|run cdd-kit upgrade/i.test(finding.message)) {
      remaining.push({
        level: 'warning',
        message: `${finding.message} (run \`cdd-kit upgrade --yes\` manually — too invasive for --fix)`,
      });
      continue;
    }

    // Anything else → not auto-fixable
    remaining.push(finding);
  }

  return { fixed, remaining };
}

/**
 * Plain-language health view (P1-2). Collapses the passing checks into a single
 * line and leads with a one-word verdict and a single "what to do next", so a
 * non-engineer can answer "is this OK, and what now?" without parsing digests or
 * chokepoint detail. The full technical list stays one `cdd-kit doctor` away.
 */
function renderSimpleReport(report: DoctorReport): void {
  const passed = report.findings.filter(f => f.level === 'ok').length;
  const warnings = report.findings.filter(f => f.level === 'warning');
  const errors = report.findings.filter(f => f.level === 'error');

  log.blank();
  log.info('cdd-kit health — plain view');
  log.blank();
  if (passed > 0) log.ok(`${passed} check${passed === 1 ? '' : 's'} passed`);
  for (const f of errors) log.error(f.message);
  for (const f of warnings) log.warn(f.message);
  log.blank();

  if (errors.length > 0) {
    log.error(`Result: there ${errors.length === 1 ? 'is 1 problem' : `are ${errors.length} problems`} to fix.`);
    log.info('Next: ask Claude to resolve the item(s) above, then re-run `cdd-kit doctor --simple`.');
  } else if (warnings.length > 0) {
    log.warn(`Result: working, but ${warnings.length} thing${warnings.length === 1 ? '' : 's'} need${warnings.length === 1 ? 's' : ''} attention.`);
    log.info('Next: run `cdd-kit doctor --fix` to auto-resolve what it can, then re-run `cdd-kit doctor --simple`.');
  } else {
    log.ok('Result: everything looks healthy.');
    log.info('Next: open Claude Code here and run `/cdd-new <describe your change>` to start a task.');
  }
  log.blank();
}

export async function doctor(opts: DoctorOptions = {}): Promise<void> {
  const cwd = process.cwd();
  let report = await buildDoctorReport(cwd, opts);

  if (opts.fix && !opts.json) {
    log.blank();
    log.info('Doctor --fix: attempting safe auto-resolutions…');
    const { fixed, remaining } = await attemptAutoFixes(cwd, report);
    for (const f of fixed) log.ok(`fixed: ${f}`);
    if (fixed.length > 0) {
      // Re-run report to refresh state
      report = await buildDoctorReport(cwd, opts);
    } else {
      log.info('no auto-fixable findings');
    }
  }

  if (opts.json) {
    console.log(JSON.stringify(report, null, 2));
    if (!report.ok) process.exit(1);
    return;
  }

  if (opts.simple) {
    renderSimpleReport(report);
    if (!report.ok) process.exit(1);
    return;
  }

  log.blank();
  log.info(`Doctor provider: ${report.provider}`);

  for (const finding of report.findings) {
    if (finding.level === 'ok') log.ok(finding.message);
    else if (finding.level === 'warning') log.warn(finding.message);
    else log.error(finding.message);
  }

  log.blank();
  if (!report.ok) {
    log.error(report.strict && report.errors === 0
      ? `doctor failed in strict mode with ${report.warnings} warning(s)`
      : `doctor failed with ${report.errors} error(s)`);
    process.exit(1);
  }

  if (report.warnings > 0) {
    log.warn(`doctor completed with ${report.warnings} warning(s)`);
  } else {
    log.ok('doctor passed');
  }
  log.blank();
}
