import { existsSync, readdirSync, readFileSync } from 'fs';
import { createHash } from 'crypto';
import { join, relative } from 'path';
import { log } from '../utils/logger.js';
import { inferProvider, validateProviderOption, type ProviderOption } from '../utils/provider.js';
import { checkCodeMapFreshness } from '../code-map/freshness.js';
import { collectAgentViolations } from './lint-agents.js';

export interface DoctorOptions {
  strict?: boolean;
  provider?: ProviderOption;
  json?: boolean;
  fix?: boolean;
}

interface Finding {
  level: 'error' | 'warning' | 'ok';
  message: string;
}

interface DoctorReport {
  provider: string;
  strict: boolean;
  findings: Finding[];
  errors: number;
  warnings: number;
  ok: boolean;
}

function fileExists(cwd: string, relPath: string): boolean {
  return existsSync(join(cwd, relPath));
}

function findFiles(dir: string, predicate: (name: string) => boolean, found: string[] = []): string[] {
  if (!existsSync(dir)) return found;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) findFiles(fullPath, predicate, found);
    else if (entry.isFile() && predicate(entry.name)) found.push(fullPath);
  }
  return found;
}

// Hash uses line-ending normalization — see src/utils/digest.ts for rationale.
import { sha256OfFileNormalized as sha256OfFile } from '../utils/digest.js';

function inputDigest(paths: string[], cwd: string): string {
  // Use repo-relative paths so the digest is portable across clones.
  // (See context-scan.ts inputsDigest for the same fix; the two MUST stay in
  // lockstep — doctor compares its computed digest against the one stamped
  // in `specs/context/*.md` by context-scan.)
  const combined = paths.slice().sort()
    .map(p => {
      const rel = relative(cwd, p).replace(/\\/g, '/');
      return `${rel}:${sha256OfFile(p)}`;
    })
    .join('\n');
  return createHash('sha256').update(combined).digest('hex');
}

function readContextIndexMetadata(filePath: string): { inputsDigest?: string; missingSummary?: number } {
  if (!existsSync(filePath)) return {};
  const text = readFileSync(filePath, 'utf8');
  const out: { inputsDigest?: string; missingSummary?: number } = {};
  const digestMatch = text.match(/^inputs-digest:\s*([a-f0-9]+)/m);
  if (digestMatch) out.inputsDigest = digestMatch[1];
  const missingMatch = text.match(/^missing-summary-count:\s*(\d+)/m);
  if (missingMatch) out.missingSummary = Number(missingMatch[1]);
  return out;
}

function checkContextFreshness(cwd: string): Finding[] {
  const findings: Finding[] = [];
  const projectMap = join(cwd, 'specs', 'context', 'project-map.md');
  const contractsIndex = join(cwd, 'specs', 'context', 'contracts-index.md');
  const contextPolicy = join(cwd, '.cdd', 'context-policy.json');
  // Mirror the file filter used by context-scan so digests align.
  const contractFiles = findFiles(
    join(cwd, 'contracts'),
    name => name.endsWith('.md') && name !== 'INDEX.md' && name !== 'CHANGELOG.md',
  );

  if (!existsSync(projectMap) || !existsSync(contractsIndex)) {
    findings.push({
      level: 'warning',
      message: 'specs/context indexes are missing; run cdd-kit context-scan before classification',
    });
    return findings;
  }

  // Hash-based freshness: compare inputs-digest in the index frontmatter against
  // the live hash of the actual input files. mtime is unreliable across git clone.
  const projectMapMeta = readContextIndexMetadata(projectMap);
  const contractsIndexMeta = readContextIndexMetadata(contractsIndex);

  const projectInputDigest = inputDigest([contextPolicy].filter(existsSync), cwd);
  if (projectMapMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (projectInputDigest && projectMapMeta.inputsDigest !== projectInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md inputs changed (.cdd/context-policy.json); re-run cdd-kit context-scan',
    });
  }

  const contractsInputDigest = inputDigest(contractFiles, cwd);
  if (contractsIndexMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (contractsInputDigest && contractsIndexMeta.inputsDigest !== contractsInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md inputs changed (contracts/*); re-run cdd-kit context-scan',
    });
  }

  if (contractsIndexMeta.missingSummary !== undefined && contractsIndexMeta.missingSummary > 0) {
    findings.push({
      level: 'warning',
      message: `contracts-index reports ${contractsIndexMeta.missingSummary} contract(s) without deterministic summary metadata`,
    });
  }

  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'context indexes are present and fresh' });
  }
  return findings;
}

function readAgentModel(path: string): string | null {
  try {
    const text = readFileSync(path, 'utf8');
    const m = text.match(/^model:\s*(\S+)/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

function checkModelPolicyDrift(cwd: string): Finding[] {
  const policyPath = join(cwd, '.cdd', 'model-policy.json');
  if (!existsSync(policyPath)) return [];

  let policy: { roles?: Record<string, string> };
  try {
    policy = JSON.parse(readFileSync(policyPath, 'utf8'));
  } catch {
    return [{ level: 'warning', message: '.cdd/model-policy.json is not valid JSON' }];
  }

  const roles = policy.roles ?? {};
  if (Object.keys(roles).length === 0) {
    return [{
      level: 'warning',
      message: '.cdd/model-policy.json has no role bindings; run cdd-kit upgrade to install defaults',
    }];
  }

  // Walk both global (~/.claude/agents) and project (.claude/agents) if present.
  const candidateDirs = [
    join(cwd, '.claude', 'agents'),
    process.env.HOME ? join(process.env.HOME, '.claude', 'agents') : '',
    process.env.USERPROFILE ? join(process.env.USERPROFILE, '.claude', 'agents') : '',
  ].filter(p => p && existsSync(p));

  if (candidateDirs.length === 0) return [];

  const findings: Finding[] = [];
  for (const [role, expected] of Object.entries(roles)) {
    let foundAny = false;
    for (const dir of candidateDirs) {
      const path = join(dir, `${role}.md`);
      if (!existsSync(path)) continue;
      foundAny = true;
      const actual = readAgentModel(path);
      if (actual && actual !== expected) {
        findings.push({
          level: 'warning',
          message: `model-policy drift: ${role} expected ${expected}, agent prompt uses ${actual} (${path})`,
        });
      }
    }
    if (!foundAny) {
      // Not installed locally; not an error — global install may still be missing this role.
    }
  }
  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'model-policy roles match installed agent prompts' });
  }
  return findings;
}

function checkAgentLint(cwd: string): Finding[] {
  const agentsDir = join(cwd, '.claude', 'agents');
  if (!existsSync(agentsDir)) return [];

  // Delegate to the single source of truth for agent-prompt shape rules so
  // doctor and `cdd-kit lint-agents` can never report different verdicts.
  const violations = collectAgentViolations(cwd);
  if (violations === null) {
    // The directory exists (checked above) but readdir failed -- a real
    // permission/IO error, not "no agents configured". Surface it instead of
    // silently reporting a clean pass.
    return [{
      level: 'warning',
      message: `lint-agents: could not read ${join('.claude', 'agents')} -- agent prompts were not scanned`,
    }];
  }

  const findings: Finding[] = violations.map(v => ({
    level: 'warning',
    message: `lint-agents: ${v.file}: [Rule ${v.rule}] ${v.message}`,
  }));

  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'lint-agents: all agent prompts pass shape checks' });
  }
  return findings;
}

function checkCodeMap(cwd: string): Finding[] {
  const findings: Finding[] = [];
  const mapPath = join(cwd, '.cdd', 'code-map.yml');
  if (!existsSync(mapPath)) {
    const probe = checkCodeMapFreshness(cwd);
    if (probe.status === 'config-error') {
      findings.push({ level: 'warning', message: `.cdd/code-map-config.yml is invalid: ${probe.configError}` });
    } else if (probe.status === 'missing-with-sources') {
      findings.push({ level: 'warning', message: '.cdd/code-map.yml is missing; run `cdd-kit code-map`' });
    }
    return findings;
  }
  const probe = checkCodeMapFreshness(cwd);
  if (probe.status === 'config-error') {
    findings.push({ level: 'warning', message: `.cdd/code-map-config.yml is invalid: ${probe.configError}` });
    return findings;
  }
  if (probe.status === 'stale') {
    const top = probe.staleFiles.slice(0, 3).join(', ');
    const more = probe.staleCount > 3 ? ` (+${probe.staleCount - 3} more)` : '';
    findings.push({ level: 'warning', message: `code-map stale: ${top}${more}; run \`cdd-kit code-map\`` });
  }
  // Compression metric from header
  const text = readFileSync(mapPath, 'utf8');
  const m = text.match(/^# files: (\d+), src-lines: (\d+), map-lines: (\d+), compression: ([\d.]+)x/m);
  if (m) {
    findings.push({ level: 'ok', message: `code-map: ${m[1]} files, ${m[4]}x compression` });
  } else {
    findings.push({ level: 'warning', message: '.cdd/code-map.yml has no metadata header (regenerate with cdd-kit 2.0.5+)' });
  }
  return findings;
}

async function buildDoctorReport(cwd: string, opts: DoctorOptions): Promise<DoctorReport> {
  const requestedProvider = opts.provider ?? 'auto';
  if (!validateProviderOption(requestedProvider)) {
    log.error(`Invalid provider: ${requestedProvider}. Use auto, claude, codex, or both.`);
    process.exit(1);
  }

  const strict = opts.strict ?? false;
  const provider = inferProvider(cwd, requestedProvider);
  const findings: Finding[] = [];

  for (const relPath of ['contracts', 'specs/templates', '.cdd/context-policy.json', '.cdd/model-policy.json']) {
    findings.push(fileExists(cwd, relPath)
      ? { level: 'ok', message: `${relPath} exists` }
      : { level: 'warning', message: `${relPath} is missing; run cdd-kit upgrade --yes` });
  }

  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'CLAUDE.md')) {
    findings.push({ level: 'warning', message: 'CLAUDE.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'AGENTS.md')) {
    findings.push({ level: 'warning', message: 'AGENTS.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'codex' || provider === 'both') && !fileExists(cwd, 'CODEX.md')) {
    findings.push({ level: 'warning', message: 'CODEX.md is missing for Codex provider; run cdd-kit upgrade --provider codex --yes' });
  }

  findings.push(...checkContextFreshness(cwd));
  findings.push(...checkModelPolicyDrift(cwd));
  findings.push(...checkAgentLint(cwd));
  findings.push(...checkCodeMap(cwd));

  const errors = findings.filter(finding => finding.level === 'error').length;
  const warnings = findings.filter(finding => finding.level === 'warning').length;
  return {
    provider,
    strict,
    findings,
    errors,
    warnings,
    ok: errors === 0 && (!strict || warnings === 0),
  };
}

async function attemptAutoFixes(cwd: string, report: DoctorReport): Promise<{ fixed: string[]; remaining: Finding[] }> {
  const fixed: string[] = [];
  const remaining: Finding[] = [];

  for (const finding of report.findings) {
    if (finding.level !== 'warning') {
      remaining.push(finding);
      continue;
    }

    // Stale or missing context indexes → run context-scan
    if (/specs\/context indexes are missing|inputs changed|older cdd-kit|older than/i.test(finding.message)) {
      try {
        const { contextScan } = await import('./context-scan.js');
        await contextScan();
        fixed.push(`ran context-scan to refresh specs/context/`);
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // code-map stale or missing → regenerate
    if (/code-map stale|code-map\.yml is missing/i.test(finding.message)) {
      try {
        const { codeMap } = await import('./code-map.js');
        await codeMap({ path: '.', out: '.cdd/code-map.yml', include: [], exclude: [], check: false, maxLines: 100000 });
        fixed.push('regenerated .cdd/code-map.yml');
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // model-policy has no role bindings → write defaults
    // (check this BEFORE the generic .cdd/* upgrade-suggestion, because the
    //  no-role-bindings message also mentions "run cdd-kit upgrade")
    if (/model-policy\.json has no role bindings/i.test(finding.message)) {
      const policyPath = join(cwd, '.cdd', 'model-policy.json');
      try {
        let existing: Record<string, unknown> = {};
        try { existing = JSON.parse(readFileSync(policyPath, 'utf8')); } catch { /* ok */ }
        const merged = {
          ...existing,
          roles: {
            'change-classifier': 'opus',
            'spec-architect': 'opus',
            'qa-reviewer': 'opus',
            'contract-reviewer': 'sonnet',
            'test-strategist': 'sonnet',
            'bug-fix-engineer': 'sonnet',
            'backend-engineer': 'sonnet',
            'frontend-engineer': 'sonnet',
            'ci-cd-gatekeeper': 'sonnet',
            'e2e-resilience-engineer': 'sonnet',
            'monkey-test-engineer': 'sonnet',
            'stress-soak-engineer': 'sonnet',
            'ui-ux-reviewer': 'sonnet',
            'visual-reviewer': 'haiku',
            'dependency-security-reviewer': 'sonnet',
            'spec-drift-auditor': 'opus',
            'repo-context-scanner': 'haiku',
          },
        };
        const { writeFileSync } = await import('fs');
        writeFileSync(policyPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
        fixed.push(`populated .cdd/model-policy.json with default role bindings`);
        continue;
      } catch (err) {
        remaining.push({ level: 'warning', message: `${finding.message} (auto-fix failed: ${(err as Error).message})` });
        continue;
      }
    }

    // .cdd/* missing → suggest upgrade (don't run upgrade automatically;
    // it can write provider-specific files the user might not want)
    if (/\.cdd\/.*is missing|run cdd-kit upgrade/i.test(finding.message)) {
      remaining.push({
        level: 'warning',
        message: `${finding.message} (run \`cdd-kit upgrade --yes\` manually — too invasive for --fix)`,
      });
      continue;
    }

    // Anything else → not auto-fixable
    remaining.push(finding);
  }

  return { fixed, remaining };
}

export async function doctor(opts: DoctorOptions = {}): Promise<void> {
  const cwd = process.cwd();
  let report = await buildDoctorReport(cwd, opts);

  if (opts.fix && !opts.json) {
    log.blank();
    log.info('Doctor --fix: attempting safe auto-resolutions…');
    const { fixed, remaining } = await attemptAutoFixes(cwd, report);
    for (const f of fixed) log.ok(`fixed: ${f}`);
    if (fixed.length > 0) {
      // Re-run report to refresh state
      report = await buildDoctorReport(cwd, opts);
    } else {
      log.info('no auto-fixable findings');
    }
  }

  if (opts.json) {
    console.log(JSON.stringify(report, null, 2));
    if (!report.ok) process.exit(1);
    return;
  }

  log.blank();
  log.info(`Doctor provider: ${report.provider}`);

  for (const finding of report.findings) {
    if (finding.level === 'ok') log.ok(finding.message);
    else if (finding.level === 'warning') log.warn(finding.message);
    else log.error(finding.message);
  }

  log.blank();
  if (!report.ok) {
    log.error(report.strict && report.errors === 0
      ? `doctor failed in strict mode with ${report.warnings} warning(s)`
      : `doctor failed with ${report.errors} error(s)`);
    process.exit(1);
  }

  if (report.warnings > 0) {
    log.warn(`doctor completed with ${report.warnings} warning(s)`);
  } else {
    log.ok('doctor passed');
  }
  log.blank();
}
