import { existsSync, readdirSync, readFileSync } from 'fs';
import { createHash } from 'crypto';
import { join } from 'path';
import { log } from '../utils/logger.js';
import { inferProvider, validateProviderOption, type ProviderOption } from '../utils/provider.js';

export interface DoctorOptions {
  strict?: boolean;
  provider?: ProviderOption;
  json?: boolean;
}

interface Finding {
  level: 'error' | 'warning' | 'ok';
  message: string;
}

interface DoctorReport {
  provider: string;
  strict: boolean;
  findings: Finding[];
  errors: number;
  warnings: number;
  ok: boolean;
}

function fileExists(cwd: string, relPath: string): boolean {
  return existsSync(join(cwd, relPath));
}

function findFiles(dir: string, predicate: (name: string) => boolean, found: string[] = []): string[] {
  if (!existsSync(dir)) return found;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) findFiles(fullPath, predicate, found);
    else if (entry.isFile() && predicate(entry.name)) found.push(fullPath);
  }
  return found;
}

function sha256OfFile(path: string): string {
  try {
    return createHash('sha256').update(readFileSync(path)).digest('hex');
  } catch {
    return '';
  }
}

function inputDigest(paths: string[]): string {
  // Sort for determinism. Each path is hashed and combined.
  const combined = paths.slice().sort()
    .map(p => `${p}:${sha256OfFile(p)}`)
    .join('\n');
  return createHash('sha256').update(combined).digest('hex');
}

function readContextIndexMetadata(filePath: string): { inputsDigest?: string; missingSummary?: number } {
  if (!existsSync(filePath)) return {};
  const text = readFileSync(filePath, 'utf8');
  const out: { inputsDigest?: string; missingSummary?: number } = {};
  const digestMatch = text.match(/^inputs-digest:\s*([a-f0-9]+)/m);
  if (digestMatch) out.inputsDigest = digestMatch[1];
  const missingMatch = text.match(/^missing-summary-count:\s*(\d+)/m);
  if (missingMatch) out.missingSummary = Number(missingMatch[1]);
  return out;
}

function checkContextFreshness(cwd: string): Finding[] {
  const findings: Finding[] = [];
  const projectMap = join(cwd, 'specs', 'context', 'project-map.md');
  const contractsIndex = join(cwd, 'specs', 'context', 'contracts-index.md');
  const contextPolicy = join(cwd, '.cdd', 'context-policy.json');
  // Mirror the file filter used by context-scan so digests align.
  const contractFiles = findFiles(
    join(cwd, 'contracts'),
    name => name.endsWith('.md') && name !== 'INDEX.md' && name !== 'CHANGELOG.md',
  );

  if (!existsSync(projectMap) || !existsSync(contractsIndex)) {
    findings.push({
      level: 'warning',
      message: 'specs/context indexes are missing; run cdd-kit context-scan before classification',
    });
    return findings;
  }

  // Hash-based freshness: compare inputs-digest in the index frontmatter against
  // the live hash of the actual input files. mtime is unreliable across git clone.
  const projectMapMeta = readContextIndexMetadata(projectMap);
  const contractsIndexMeta = readContextIndexMetadata(contractsIndex);

  const projectInputDigest = inputDigest([contextPolicy].filter(existsSync));
  if (projectMapMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (projectInputDigest && projectMapMeta.inputsDigest !== projectInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/project-map.md inputs changed (.cdd/context-policy.json); re-run cdd-kit context-scan',
    });
  }

  const contractsInputDigest = inputDigest(contractFiles);
  if (contractsIndexMeta.inputsDigest === undefined) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md was generated by an older cdd-kit (no inputs-digest); re-run cdd-kit context-scan',
    });
  } else if (contractsInputDigest && contractsIndexMeta.inputsDigest !== contractsInputDigest) {
    findings.push({
      level: 'warning',
      message: 'specs/context/contracts-index.md inputs changed (contracts/*); re-run cdd-kit context-scan',
    });
  }

  if (contractsIndexMeta.missingSummary !== undefined && contractsIndexMeta.missingSummary > 0) {
    findings.push({
      level: 'warning',
      message: `contracts-index reports ${contractsIndexMeta.missingSummary} contract(s) without deterministic summary metadata`,
    });
  }

  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'context indexes are present and fresh' });
  }
  return findings;
}

function readAgentModel(path: string): string | null {
  try {
    const text = readFileSync(path, 'utf8');
    const m = text.match(/^model:\s*(\S+)/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

function checkModelPolicyDrift(cwd: string): Finding[] {
  const policyPath = join(cwd, '.cdd', 'model-policy.json');
  if (!existsSync(policyPath)) return [];

  let policy: { roles?: Record<string, string> };
  try {
    policy = JSON.parse(readFileSync(policyPath, 'utf8'));
  } catch {
    return [{ level: 'warning', message: '.cdd/model-policy.json is not valid JSON' }];
  }

  const roles = policy.roles ?? {};
  if (Object.keys(roles).length === 0) {
    return [{
      level: 'warning',
      message: '.cdd/model-policy.json has no role bindings; run cdd-kit upgrade to install defaults',
    }];
  }

  // Walk both global (~/.claude/agents) and project (.claude/agents) if present.
  const candidateDirs = [
    join(cwd, '.claude', 'agents'),
    process.env.HOME ? join(process.env.HOME, '.claude', 'agents') : '',
    process.env.USERPROFILE ? join(process.env.USERPROFILE, '.claude', 'agents') : '',
  ].filter(p => p && existsSync(p));

  if (candidateDirs.length === 0) return [];

  const findings: Finding[] = [];
  for (const [role, expected] of Object.entries(roles)) {
    let foundAny = false;
    for (const dir of candidateDirs) {
      const path = join(dir, `${role}.md`);
      if (!existsSync(path)) continue;
      foundAny = true;
      const actual = readAgentModel(path);
      if (actual && actual !== expected) {
        findings.push({
          level: 'warning',
          message: `model-policy drift: ${role} expected ${expected}, agent prompt uses ${actual} (${path})`,
        });
      }
    }
    if (!foundAny) {
      // Not installed locally; not an error — global install may still be missing this role.
    }
  }
  if (findings.length === 0) {
    findings.push({ level: 'ok', message: 'model-policy roles match installed agent prompts' });
  }
  return findings;
}

function buildDoctorReport(cwd: string, opts: DoctorOptions): DoctorReport {
  const requestedProvider = opts.provider ?? 'auto';
  if (!validateProviderOption(requestedProvider)) {
    log.error(`Invalid provider: ${requestedProvider}. Use auto, claude, codex, or both.`);
    process.exit(1);
  }

  const strict = opts.strict ?? false;
  const provider = inferProvider(cwd, requestedProvider);
  const findings: Finding[] = [];

  for (const relPath of ['contracts', 'specs/templates', '.cdd/context-policy.json', '.cdd/model-policy.json']) {
    findings.push(fileExists(cwd, relPath)
      ? { level: 'ok', message: `${relPath} exists` }
      : { level: 'warning', message: `${relPath} is missing; run cdd-kit upgrade --yes` });
  }

  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'CLAUDE.md')) {
    findings.push({ level: 'warning', message: 'CLAUDE.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'claude' || provider === 'both') && !fileExists(cwd, 'AGENTS.md')) {
    findings.push({ level: 'warning', message: 'AGENTS.md is missing for Claude provider; run cdd-kit upgrade --provider claude --yes' });
  }
  if ((provider === 'codex' || provider === 'both') && !fileExists(cwd, 'CODEX.md')) {
    findings.push({ level: 'warning', message: 'CODEX.md is missing for Codex provider; run cdd-kit upgrade --provider codex --yes' });
  }

  findings.push(...checkContextFreshness(cwd));
  findings.push(...checkModelPolicyDrift(cwd));

  const errors = findings.filter(finding => finding.level === 'error').length;
  const warnings = findings.filter(finding => finding.level === 'warning').length;
  return {
    provider,
    strict,
    findings,
    errors,
    warnings,
    ok: errors === 0 && (!strict || warnings === 0),
  };
}

export async function doctor(opts: DoctorOptions = {}): Promise<void> {
  const report = buildDoctorReport(process.cwd(), opts);

  if (opts.json) {
    console.log(JSON.stringify(report, null, 2));
    if (!report.ok) process.exit(1);
    return;
  }

  log.blank();
  log.info(`Doctor provider: ${report.provider}`);

  for (const finding of report.findings) {
    if (finding.level === 'ok') log.ok(finding.message);
    else if (finding.level === 'warning') log.warn(finding.message);
    else log.error(finding.message);
  }

  log.blank();
  if (!report.ok) {
    log.error(report.strict && report.errors === 0
      ? `doctor failed in strict mode with ${report.warnings} warning(s)`
      : `doctor failed with ${report.errors} error(s)`);
    process.exit(1);
  }

  if (report.warnings > 0) {
    log.warn(`doctor completed with ${report.warnings} warning(s)`);
  } else {
    log.ok('doctor passed');
  }
  log.blank();
}
