import { existsSync, writeFileSync } from 'fs';
import { join } from 'path';
import { log } from '../utils/logger.js';
import { getTouchedPaths } from '../utils/git-paths.js';
import { resolveTier } from './gate-tier.js';

export interface ManifestOptions {
  force?: boolean;
  json?: boolean;
}

/**
 * The lowest-risk tiers a micro-change can carry. Auto-generation is restricted
 * to these: for tier 0-3 the full hand-authored manifest (with explicit agent
 * work packets and a deliberately scoped Allowed Paths) is the point of the
 * ceremony — a critical/behavioral change should not get a rubber-stamped
 * "whatever it touched is allowed" boundary. Tier 4 = low risk, 5 = doc-only.
 */
const MIN_AUTO_TIER = 4;

/** The three paths every change's agents may always read (see the template). */
const DEFAULT_ALLOWED = (changeId: string): string[] => [
  `specs/changes/${changeId}/`,
  'specs/context/project-map.md',
  'specs/context/contracts-index.md',
];

function printJson(value: unknown): void {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}

/**
 * Repo-relative touched paths that belong in a micro-change's Allowed Paths:
 * the files the change actually edits, minus anything already covered by the
 * `specs/changes/<id>/` default (the change's own artifacts) and any OTHER
 * change's directory (never this change's read scope). Sorted + de-duplicated.
 */
function changeRelevantPaths(cwd: string, changeId: string): string[] {
  const ownDir = `specs/changes/${changeId}/`;
  const touched = getTouchedPaths(cwd)
    .map(p => p.replace(/\\/g, '/'))
    .filter(p => !p.startsWith(ownDir))
    .filter(p => !p.startsWith('specs/changes/'));
  return [...new Set(touched)].sort();
}

function renderManifest(changeId: string, tier: number, allowed: string[], surfaces: string[]): string {
  const surfaceLines = surfaces.length > 0
    ? surfaces.map(s => `- ${s}`).join('\n')
    : '- (none detected yet — add the surfaces this change touches)';
  return [
    '# Context Manifest',
    '',
    `<!-- Auto-generated by \`cdd-kit manifest ${changeId}\` for a low-risk tier ${tier} change.`,
    '     Allowed Paths = this change\'s directory + the files it currently touches.',
    '     Re-run after editing more files, or add paths by hand — the gate validates',
    '     every agent\'s files-read log against this list. -->',
    '',
    '## Affected Surfaces',
    surfaceLines,
    '',
    '## Allowed Paths',
    allowed.map(p => `- ${p}`).join('\n'),
    '',
    '## Required Contracts',
    '-',
    '',
    '## Required Tests',
    '-',
    '',
    '## Context Expansion Requests',
    '-',
    '',
    '## Approved Expansions',
    '-',
    '',
  ].join('\n');
}

/**
 * Generate a minimal context-manifest.md for a low-risk (tier 4-5) micro-change
 * (P2-6). The manifest's Allowed Paths is the change directory plus the files
 * the change touches — enough to satisfy read-scope governance without the
 * author hand-writing a full manifest for a trivial edit. Refuses to run for a
 * tier stricter than MIN_AUTO_TIER (where the full ceremony is intentional) and
 * never clobbers an existing manifest unless `--force` is given.
 */
export function manifest(changeId: string, opts: ManifestOptions = {}): number {
  const cwd = process.cwd();
  const changeDir = join(cwd, 'specs', 'changes', changeId);

  const fail = (message: string): number => {
    if (opts.json) printJson({ error: message });
    else log.error(message);
    return 1;
  };

  if (!existsSync(changeDir)) {
    return fail(`change not found: ${changeId} (looked in specs/changes/${changeId})`);
  }

  const { tier } = resolveTier(changeDir);
  if (tier === null) {
    return fail(
      `cannot auto-generate a manifest for ${changeId}: no tier is set yet. ` +
      'Classify the change first (set `tier: <0-5>` in tasks.yml frontmatter), then re-run.',
    );
  }
  if (tier < MIN_AUTO_TIER) {
    return fail(
      `manifest auto-generation is only for low-risk tier ${MIN_AUTO_TIER}-5 micro-changes; ` +
      `${changeId} is tier ${tier}. Author a full context-manifest.md from the template — ` +
      'a stricter change needs deliberately scoped Allowed Paths and per-agent work packets.',
    );
  }

  const manifestPath = join(changeDir, 'context-manifest.md');
  if (existsSync(manifestPath) && !opts.force) {
    return fail(
      `context-manifest.md already exists for ${changeId}; refusing to overwrite a manifest you may have ` +
      'hand-authored. Re-run with --force to regenerate it from the current touched files.',
    );
  }

  const touched = changeRelevantPaths(cwd, changeId);
  const allowed = [...DEFAULT_ALLOWED(changeId), ...touched];
  const body = renderManifest(changeId, tier, allowed, touched);
  writeFileSync(manifestPath, body, 'utf8');

  if (opts.json) {
    printJson({
      'change-id': changeId,
      tier,
      path: `specs/changes/${changeId}/context-manifest.md`,
      allowed_paths: allowed,
      touched,
      written: true,
    });
    return 0;
  }

  log.ok(`Generated minimal context-manifest.md for ${changeId} (tier ${tier}).`);
  log.dim(`  Allowed Paths: ${allowed.length} (${touched.length} touched file(s) + ${DEFAULT_ALLOWED(changeId).length} defaults)`);
  if (touched.length === 0) {
    log.dim('  No changed files detected yet — Allowed Paths has the defaults only; re-run after editing, or add paths by hand.');
  }
  log.dim('  Review specs/changes/' + changeId + '/context-manifest.md and adjust if an agent needs more.');
  return 0;
}
