import { join } from 'path';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'fs';
import { log } from '../utils/logger.js';

interface MigrateOptions {
  all?: boolean;
  dryRun?: boolean;
  enableContextGovernance?: boolean;
  noBackup?: boolean;
}

interface MigrateResult {
  changed: string[];
  warnings: string[];
}

interface PendingWrite {
  path: string;
  content: string;
}

function backupChangeDir(cwd: string, changeId: string, sessionStamp: string): string {
  const backupRoot = join(cwd, '.cdd', 'migrate-backup', sessionStamp);
  const backupDir = join(backupRoot, changeId);
  mkdirSync(backupRoot, { recursive: true });
  const sourceDir = join(cwd, 'specs', 'changes', changeId);
  if (existsSync(sourceDir)) {
    cpSync(sourceDir, backupDir, { recursive: true });
  }
  return backupDir;
}

function buildLegacyContextManifest(changeId: string): string {
  return [
    '# Context Manifest',
    '',
    'Generated by `cdd-kit migrate` for an existing change.',
    'Legacy manifest. Forbidden paths come from `.cdd/context-policy.json`.',
    '',
    '## Affected Surfaces',
    '- legacy-unknown',
    '',
    '## Allowed Paths',
    `- specs/changes/${changeId}/`,
    '',
    '## Required Contracts',
    '- legacy-unknown',
    '',
    '## Required Tests',
    '- legacy-unknown',
    '',
    '## Agent Work Packets',
    '',
    '## Context Expansion Requests',
    '-',
    '',
    '## Approved Expansions',
    '-',
    '',
  ].join('\n');
}

function upsertFrontmatterField(content: string, field: string, value: string): string {
  if (!content.startsWith('---\n')) return content;
  const closing = content.indexOf('\n---', 4);
  if (closing === -1) return content;

  const frontmatter = content.slice(4, closing);
  const body = content.slice(closing);
  const fieldPattern = new RegExp(`^${field}:.*$`, 'm');
  const nextFrontmatter = fieldPattern.test(frontmatter)
    ? frontmatter.replace(fieldPattern, `${field}: ${value}`)
    : `${frontmatter.trimEnd()}\n${field}: ${value}`;

  return `---\n${nextFrontmatter}${body}`;
}

function buildContextGovernedManifest(changeId: string): string {
  return [
    '# Context Manifest',
    '',
    'Generated by `cdd-kit migrate --enable-context-governance` for an existing change.',
    'Review and narrow the allowed paths before assigning implementation work.',
    'Forbidden paths come from `.cdd/context-policy.json`.',
    '',
    '## Affected Surfaces',
    '- legacy-unknown',
    '',
    '## Allowed Paths',
    `- specs/changes/${changeId}/`,
    '- specs/context/project-map.md',
    '- specs/context/contracts-index.md',
    '',
    '## Required Contracts',
    '- legacy-unknown',
    '',
    '## Required Tests',
    '- legacy-unknown',
    '',
    '## Agent Work Packets',
    '',
    '### change-classifier',
    '- allowed:',
    `  - specs/changes/${changeId}/`,
    '  - specs/context/project-map.md',
    '  - specs/context/contracts-index.md',
    '',
    '## Context Expansion Requests',
    '',
    '<!--',
    'Agents must request context expansion instead of reading outside their work packet.',
    'Use this format only for real requests:',
    '',
    '- request-id: CER-001',
    '  requested_paths:',
    '    - src/example.ts',
    '  reason: why this file is required',
    '  status: pending',
    '-->',
    '',
    '## Approved Expansions',
    '-',
    '',
  ].join('\n');
}

function migrateOne(changeId: string, changeDir: string, enableContextGovernance: boolean): { result: MigrateResult; pending: PendingWrite[] } {
  const changed: string[] = [];
  const warnings: string[] = [];
  const pending: PendingWrite[] = [];
  let detectedTier: string | null = null;

  // ── tasks.md: add YAML frontmatter + legend ──────────────────────────────
  const tasksPath = join(changeDir, 'tasks.md');
  if (existsSync(tasksPath)) {
    let content = readFileSync(tasksPath, 'utf8');
    const norm = content.replace(/\r\n/g, '\n');
    let modified = false;
    const taskChanges: string[] = [];

    if (!norm.startsWith('---')) {
      const bareStatusMatch = norm.match(/^status:\s*(\S+)/m);
      const inferredStatus = bareStatusMatch ? bareStatusMatch[1] : 'in-progress';

      if (bareStatusMatch) {
        content = content.replace(/^status:\s*\S+[ \t]*\n?/m, '');
      }

      content = `---\nchange-id: ${changeId}\nstatus: ${inferredStatus}\n---\n\n` + content;
      modified = true;
      taskChanges.push('added YAML frontmatter');
    }

    if (!content.includes('[x]=done')) {
      content = content.replace(
        /^(---\n[\s\S]*?---\n)/,
        `$1\n<!-- [x]=done [-]=N/A [ ]=pending -->\n`,
      );
      modified = true;
      taskChanges.push('added [x]/[-]/[ ] legend comment');
    }

    if (enableContextGovernance && !/^context-governance:\s*v1\b/m.test(content)) {
      content = upsertFrontmatterField(content, 'context-governance', 'v1');
      modified = true;
      taskChanges.push('enabled context-governance: v1');
    }

    if (modified) {
      changed.push(`tasks.md: ${taskChanges.join('; ')}`);
      pending.push({ path: tasksPath, content });
    }
  } else {
    warnings.push('tasks.md not found — skipping frontmatter migration');
  }

  // ── change-classification.md: detect tier and append structured form if missing ──
  const classifPath = join(changeDir, 'change-classification.md');
  if (existsSync(classifPath)) {
    const content = readFileSync(classifPath, 'utf8');
    const hasNewTierFormat = /^## Tier\s*\n\s*-\s*\d\s*$/m.test(content);
    const oldMatch = content.match(/\*\*Tier[:\*]+\s*(?:Tier\s*)?(\d)/i)
      ?? content.match(/^-?\s*Tier:\s*(?:Tier\s*)?(\d)/mi);
    if (oldMatch) detectedTier = oldMatch[1];

    if (!hasNewTierFormat) {
      if (detectedTier) {
        const addition = `\n## Tier\n- ${detectedTier}\n`;
        if (!content.includes('\n## Tier\n')) {
          changed.push(
            `change-classification.md: appended "## Tier\\n- ${detectedTier}" (converted from old format)`,
          );
          pending.push({ path: classifPath, content: content + addition });
        }
      } else {
        warnings.push(
          'change-classification.md: could not detect tier (no **Tier:** N or ## Tier N found). ' +
          'Set `tier: <0-5>` in tasks.md frontmatter to enable tier-based gate checks.',
        );
      }
    } else {
      const structured = content.match(/^## Tier\s*\n\s*-\s*(\d)\s*$/m);
      if (structured) detectedTier = structured[1];
    }
  }

  // ── tasks.md frontmatter: backfill `tier:` and `archive-tasks:` (B1+B2) ──
  if (existsSync(tasksPath)) {
    const tasksWrite = pending.find(p => p.path === tasksPath);
    let content = tasksWrite ? tasksWrite.content : readFileSync(tasksPath, 'utf8');
    let modified = false;
    const subChanges: string[] = [];

    if (detectedTier && !/^tier:\s*\d/m.test(content)) {
      content = upsertFrontmatterField(content, 'tier', detectedTier);
      modified = true;
      subChanges.push(`backfilled tier: ${detectedTier}`);
    }

    if (!/^archive-tasks:/m.test(content)) {
      content = upsertFrontmatterField(content, 'archive-tasks', '["7.1", "7.2"]');
      modified = true;
      subChanges.push('added default archive-tasks list');
    }

    if (modified) {
      if (tasksWrite) {
        tasksWrite.content = content;
      } else {
        pending.push({ path: tasksPath, content });
      }
      changed.push(`tasks.md: ${subChanges.join('; ')}`);
    }
  }

  const manifestPath = join(changeDir, 'context-manifest.md');
  if (!existsSync(manifestPath)) {
    changed.push(enableContextGovernance
      ? 'context-manifest.md: added context-governance v1 manifest scaffold'
      : 'context-manifest.md: added legacy context manifest scaffold');
    pending.push({
      path: manifestPath,
      content: enableContextGovernance ? buildContextGovernedManifest(changeId) : buildLegacyContextManifest(changeId),
    });
  } else if (enableContextGovernance) {
    warnings.push('context-manifest.md already exists — review allowed paths before relying on context-governance: v1');
  }

  return { result: { changed, warnings }, pending };
}

function commitWritesAtomically(pending: PendingWrite[]): void {
  // Two-phase: write all to .tmp siblings first, then rename. If any tmp write
  // fails, throw before any rename happens. Rename is atomic on POSIX.
  const renames: Array<{ tmp: string; final: string }> = [];
  try {
    for (const write of pending) {
      const tmp = `${write.path}.cdd-migrate.tmp`;
      writeFileSync(tmp, write.content, 'utf8');
      renames.push({ tmp, final: write.path });
    }
  } catch (err) {
    for (const r of renames) {
      try { rmSync(r.tmp, { force: true }); } catch { /* ignore */ }
    }
    throw err;
  }
  // Phase 2: rename. If any rename fails partway through we still leave the
  // remaining tmp files for the operator to inspect, but the backup at
  // .cdd/migrate-backup/<stamp>/ is the recovery source of truth.
  for (const r of renames) {
    renameSync(r.tmp, r.final);
  }
}

export async function migrate(changeId?: string, opts: MigrateOptions = {}): Promise<void> {
  const cwd = process.cwd();
  const dryRun = opts.dryRun ?? false;
  const enableContextGovernance = opts.enableContextGovernance ?? false;
  const noBackup = opts.noBackup ?? false;

  const idsToMigrate: string[] = [];

  if (opts.all) {
    const changesDir = join(cwd, 'specs', 'changes');
    if (!existsSync(changesDir)) {
      log.info('No specs/changes/ directory found — nothing to migrate.');
      return;
    }
    idsToMigrate.push(
      ...readdirSync(changesDir, { withFileTypes: true })
        .filter(d => d.isDirectory())
        .map(d => d.name),
    );
  } else if (changeId) {
    const specificDir = join(cwd, 'specs', 'changes', changeId);
    if (!existsSync(specificDir)) {
      log.error(`Change not found: specs/changes/${changeId}`);
      process.exit(1);
    }
    idsToMigrate.push(changeId);
  } else {
    log.error('Usage: cdd-kit migrate <change-id>  |  cdd-kit migrate --all  [--dry-run] [--no-backup]');
    process.exit(1);
  }

  if (idsToMigrate.length === 0) {
    log.info('No changes found to migrate.');
    return;
  }

  if (dryRun) {
    log.info('Dry run — no files will be written.');
    log.blank();
  }

  const sessionStamp = new Date().toISOString().replace(/[:.]/g, '-');
  let migratedCount = 0;
  let upToDateCount = 0;
  const backupRoot = join(cwd, '.cdd', 'migrate-backup', sessionStamp);

  for (const id of idsToMigrate) {
    const changeDir = join(cwd, 'specs', 'changes', id);
    if (!existsSync(changeDir)) {
      log.warn(`  ${id}: directory not found — skipping`);
      continue;
    }

    const { result, pending } = migrateOne(id, changeDir, enableContextGovernance);
    const { changed, warnings } = result;

    if (changed.length === 0) {
      log.info(`  ${id}: already up to date`);
      upToDateCount++;
      for (const w of warnings) log.warn(`  ${id}: ${w}`);
      continue;
    }

    if (!dryRun) {
      try {
        if (!noBackup) backupChangeDir(cwd, id, sessionStamp);
        commitWritesAtomically(pending);
      } catch (err) {
        log.error(`  ${id}: migration failed — ${(err as Error).message}`);
        if (!noBackup) {
          log.error(`  ${id}: restore from .cdd/migrate-backup/${sessionStamp}/${id}/`);
        }
        process.exit(1);
      }
    }

    log.ok(`  ${id}: migrated`);
    for (const c of changed) log.info(`    + ${c}`);
    migratedCount++;
    for (const w of warnings) log.warn(`  ${id}: ${w}`);
  }

  log.blank();
  if (dryRun) {
    log.info(`Dry run complete: ${migratedCount} change(s) would be updated, ${upToDateCount} already up to date.`);
  } else {
    log.ok(`Migration complete: ${migratedCount} updated, ${upToDateCount} already up to date.`);
    if (migratedCount > 0 && !noBackup) {
      log.info(`Backup: ${backupRoot}`);
      log.info('Next: git add specs/changes/ && git commit -m "chore: migrate changes to current cdd-kit format"');
      log.info('When stable, remove backup: rm -rf .cdd/migrate-backup/');
    }
  }
}
