import { join } from 'path';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'fs';
import yaml from 'js-yaml';
import { log } from '../utils/logger.js';

interface MigrateOptions {
  all?: boolean;
  dryRun?: boolean;
  enableContextGovernance?: boolean;
  noBackup?: boolean;
}

interface MigrateResult {
  changed: string[];
  warnings: string[];
}

interface PendingWrite {
  path: string;
  content: string;
}

interface PendingDelete {
  path: string;
}

function backupChangeDir(cwd: string, changeId: string, sessionStamp: string): string {
  const backupRoot = join(cwd, '.cdd', 'migrate-backup', sessionStamp);
  const backupDir = join(backupRoot, changeId);
  mkdirSync(backupRoot, { recursive: true });
  const sourceDir = join(cwd, 'specs', 'changes', changeId);
  if (existsSync(sourceDir)) {
    cpSync(sourceDir, backupDir, { recursive: true });
  }
  return backupDir;
}

function buildLegacyContextManifest(changeId: string): string {
  return [
    '# Context Manifest',
    '',
    'Generated by `cdd-kit migrate` for an existing change.',
    'Legacy manifest. Forbidden paths come from `.cdd/context-policy.json`.',
    '',
    '## Affected Surfaces',
    '- legacy-unknown',
    '',
    '## Allowed Paths',
    `- specs/changes/${changeId}/`,
    '',
    '## Required Contracts',
    '- legacy-unknown',
    '',
    '## Required Tests',
    '- legacy-unknown',
    '',
    '## Agent Work Packets',
    '',
    '## Context Expansion Requests',
    '-',
    '',
    '## Approved Expansions',
    '-',
    '',
  ].join('\n');
}

function buildContextGovernedManifest(changeId: string): string {
  return [
    '# Context Manifest',
    '',
    'Generated by `cdd-kit migrate --enable-context-governance` for an existing change.',
    'Review and narrow the allowed paths before assigning implementation work.',
    'Forbidden paths come from `.cdd/context-policy.json`.',
    '',
    '## Affected Surfaces',
    '- legacy-unknown',
    '',
    '## Allowed Paths',
    `- specs/changes/${changeId}/`,
    '- specs/context/project-map.md',
    '- specs/context/contracts-index.md',
    '',
    '## Required Contracts',
    '- legacy-unknown',
    '',
    '## Required Tests',
    '- legacy-unknown',
    '',
    '## Agent Work Packets',
    '',
    '### change-classifier',
    '- allowed:',
    `  - specs/changes/${changeId}/`,
    '  - specs/context/project-map.md',
    '  - specs/context/contracts-index.md',
    '',
    '## Context Expansion Requests',
    '',
    '<!--',
    'Agents must request context expansion instead of reading outside their work packet.',
    'Use this format only for real requests:',
    '',
    '- request-id: CER-001',
    '  requested_paths:',
    '    - src/example.ts',
    '  reason: why this file is required',
    '  status: pending',
    '-->',
    '',
    '## Approved Expansions',
    '-',
    '',
  ].join('\n');
}

function parseLegacyFrontmatter(content: string): Record<string, string> {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out: Record<string, string> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const colon = line.indexOf(':');
    if (colon === -1) continue;
    const key = line.slice(0, colon).trim();
    if (!key) continue;
    out[key] = line.slice(colon + 1).trim();
  }
  return out;
}

function parseListField(raw: string | undefined): string[] {
  if (!raw) return [];
  const trimmed = raw.trim();
  if (!trimmed || trimmed === '[]') return [];
  const inner = trimmed.startsWith('[') && trimmed.endsWith(']') ? trimmed.slice(1, -1) : trimmed;
  return inner
    .split(',')
    .map(item => item.trim().replace(/^["']|["']$/g, ''))
    .filter(Boolean);
}

interface LegacyTaskRow {
  id: string;
  section?: string;
  title: string;
  status: 'pending' | 'done' | 'skipped';
}

function parseLegacyTaskList(body: string): LegacyTaskRow[] {
  const lines = body.split(/\r?\n/);
  const rows: LegacyTaskRow[] = [];
  let currentSection: string | undefined;
  for (const raw of lines) {
    const headerMatch = raw.match(/^##\s+\d+\.\s+(.*)\s*$/);
    if (headerMatch) {
      currentSection = headerMatch[1].trim();
      continue;
    }
    const itemMatch = raw.match(/^\s*-\s*\[([ xX\-])\]\s+(\d+(?:\.\d+)*)\s+(.*)\s*$/);
    if (!itemMatch) continue;
    const mark = itemMatch[1];
    const id = itemMatch[2];
    const title = itemMatch[3].trim();
    let status: 'pending' | 'done' | 'skipped' = 'pending';
    if (mark === 'x' || mark === 'X') status = 'done';
    else if (mark === '-') status = 'skipped';
    rows.push({ id, title, status, section: currentSection });
  }
  return rows;
}

function migrateTasksFile(
  changeId: string,
  changeDir: string,
  enableContextGovernance: boolean,
  detectedTier: string | null,
  changed: string[],
  warnings: string[],
  pendingWrites: PendingWrite[],
  pendingDeletes: PendingDelete[],
): void {
  const newPath = join(changeDir, 'tasks.yml');
  const legacyPath = join(changeDir, 'tasks.md');

  if (existsSync(newPath)) {
    return;
  }

  if (!existsSync(legacyPath)) {
    warnings.push('tasks.md not found and tasks.yml missing — skipping tasks migration');
    return;
  }

  const raw = readFileSync(legacyPath, 'utf8');
  const fm = parseLegacyFrontmatter(raw);
  const bodyMatch = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?([\s\S]*)$/);
  const body = bodyMatch ? bodyMatch[1] : raw;

  const tasksRows = parseLegacyTaskList(body);

  const data: Record<string, unknown> = {};
  data['change-id'] = fm['change-id'] || changeId;
  data['status'] = fm['status'] || 'in-progress';

  if (fm['tier'] && /^\d+$/.test(fm['tier'])) {
    data['tier'] = parseInt(fm['tier'], 10);
  } else if (detectedTier) {
    data['tier'] = parseInt(detectedTier, 10);
  } else {
    data['tier'] = null;
  }

  if (enableContextGovernance || fm['context-governance'] === 'v1') {
    data['context-governance'] = 'v1';
  }

  const archive = parseListField(fm['archive-tasks']);
  data['archive-tasks'] = archive.length > 0 ? archive : ['7.1', '7.2'];

  const deps = parseListField(fm['depends-on']);
  data['depends-on'] = deps;

  data['tasks'] = tasksRows.map(r => {
    const out: Record<string, unknown> = { id: r.id, title: r.title, status: r.status };
    if (r.section) out['section'] = r.section;
    return out;
  });

  const yamlOut = yaml.dump(data, { lineWidth: -1, noRefs: true });
  pendingWrites.push({ path: newPath, content: yamlOut });
  pendingDeletes.push({ path: legacyPath });
  changed.push(`tasks.md -> tasks.yml (${tasksRows.length} task(s) migrated)`);
}

function parseLegacyAgentLog(content: string): Record<string, unknown> {
  const lines = content.split(/\r?\n/);
  const data: Record<string, unknown> = {};
  let i = 0;
  // Top-level field pattern: optional 0-1 spaces, then "- key:"
  const topFieldRe = /^[ ]{0,1}-\s*([\w-]+):\s*(.*)$/;
  while (i < lines.length) {
    const line = lines[i];
    const fieldMatch = line.match(topFieldRe);
    if (!fieldMatch) {
      i++;
      continue;
    }
    const key = fieldMatch[1];
    const inline = fieldMatch[2].trim();

    if (key === 'files-read' || key === 'artifacts') {
      const items: string[] = [];
      let j = i + 1;
      while (j < lines.length) {
        const sub = lines[j];
        if (topFieldRe.test(sub)) break;
        if (/^#/.test(sub)) break;
        const itemMatch = sub.match(/^\s{2,}-\s+(.+?)\s*$/);
        if (itemMatch) {
          items.push(itemMatch[1].trim());
        }
        j++;
      }
      if (key === 'files-read') {
        data['files-read'] = items;
      } else {
        data['artifacts'] = items.map(s => {
          const idx = s.indexOf(':');
          if (idx === -1) {
            return { type: 'note', pointer: s };
          }
          const type = s.slice(0, idx).trim();
          const pointer = s.slice(idx + 1).trim();
          return { type, pointer };
        });
      }
      i = j;
      continue;
    }

    data[key] = inline;
    i++;
  }
  return data;
}

function migrateAgentLogs(
  changeDir: string,
  changed: string[],
  pendingWrites: PendingWrite[],
  pendingDeletes: PendingDelete[],
): void {
  const agentLogDir = join(changeDir, 'agent-log');
  if (!existsSync(agentLogDir)) return;

  const mdLogs = readdirSync(agentLogDir).filter(f => f.endsWith('.md'));
  for (const f of mdLogs) {
    const fullPath = join(agentLogDir, f);
    const yamlName = f.replace(/\.md$/, '.yml');
    const yamlFull = join(agentLogDir, yamlName);
    if (existsSync(yamlFull)) continue;

    const raw = readFileSync(fullPath, 'utf8');
    const parsed = parseLegacyAgentLog(raw);
    const yamlOut = yaml.dump(parsed, { lineWidth: -1, noRefs: true });
    pendingWrites.push({ path: yamlFull, content: yamlOut });
    pendingDeletes.push({ path: fullPath });
    changed.push(`agent-log/${f} -> agent-log/${yamlName}`);
  }
}

function migrateOne(changeId: string, changeDir: string, enableContextGovernance: boolean): { result: MigrateResult; pending: PendingWrite[]; deletes: PendingDelete[] } {
  const changed: string[] = [];
  const warnings: string[] = [];
  const pending: PendingWrite[] = [];
  const deletes: PendingDelete[] = [];
  let detectedTier: string | null = null;

  // change-classification.md tier detection
  const classifPath = join(changeDir, 'change-classification.md');
  if (existsSync(classifPath)) {
    const content = readFileSync(classifPath, 'utf8');
    const hasNewTierFormat = /^## Tier\s*\n\s*-\s*\d\s*$/m.test(content);
    const oldMatch = content.match(/\*\*Tier[:\*]+\s*(?:Tier\s*)?(\d)/i)
      ?? content.match(/^-?\s*Tier:\s*(?:Tier\s*)?(\d)/mi);
    if (oldMatch) detectedTier = oldMatch[1];

    if (!hasNewTierFormat) {
      if (detectedTier) {
        const addition = `\n## Tier\n- ${detectedTier}\n`;
        if (!content.includes('\n## Tier\n')) {
          changed.push(
            `change-classification.md: appended "## Tier\\n- ${detectedTier}" (converted from old format)`,
          );
          pending.push({ path: classifPath, content: content + addition });
        }
      } else {
        warnings.push(
          'change-classification.md: could not detect tier (no **Tier:** N or ## Tier N found). ' +
          'Set `tier: <0-5>` in tasks.yml frontmatter to enable tier-based gate checks.',
        );
      }
    } else {
      const structured = content.match(/^## Tier\s*\n\s*-\s*(\d)\s*$/m);
      if (structured) detectedTier = structured[1];
    }
  }

  // tasks.md -> tasks.yml
  migrateTasksFile(changeId, changeDir, enableContextGovernance, detectedTier, changed, warnings, pending, deletes);

  // agent-log/*.md -> agent-log/*.yml
  migrateAgentLogs(changeDir, changed, pending, deletes);

  // context-manifest.md
  const manifestPath = join(changeDir, 'context-manifest.md');
  if (!existsSync(manifestPath)) {
    changed.push(enableContextGovernance
      ? 'context-manifest.md: added context-governance v1 manifest scaffold'
      : 'context-manifest.md: added legacy context manifest scaffold');
    pending.push({
      path: manifestPath,
      content: enableContextGovernance ? buildContextGovernedManifest(changeId) : buildLegacyContextManifest(changeId),
    });
  } else if (enableContextGovernance) {
    warnings.push('context-manifest.md already exists — review allowed paths before relying on context-governance: v1');
  }

  return { result: { changed, warnings }, pending, deletes };
}

function commitWritesAtomically(pending: PendingWrite[], deletes: PendingDelete[]): void {
  const renames: Array<{ tmp: string; final: string }> = [];
  try {
    for (const write of pending) {
      const tmp = `${write.path}.cdd-migrate.tmp`;
      writeFileSync(tmp, write.content, 'utf8');
      renames.push({ tmp, final: write.path });
    }
  } catch (err) {
    for (const r of renames) {
      try { rmSync(r.tmp, { force: true }); } catch { /* ignore */ }
    }
    throw err;
  }
  for (const r of renames) {
    renameSync(r.tmp, r.final);
  }
  for (const d of deletes) {
    try { rmSync(d.path, { force: true }); } catch { /* ignore */ }
  }
}

export async function migrate(changeId?: string, opts: MigrateOptions = {}): Promise<void> {
  const cwd = process.cwd();
  const dryRun = opts.dryRun ?? false;
  const enableContextGovernance = opts.enableContextGovernance ?? false;
  const noBackup = opts.noBackup ?? false;

  const idsToMigrate: string[] = [];

  if (opts.all) {
    const changesDir = join(cwd, 'specs', 'changes');
    if (!existsSync(changesDir)) {
      log.info('No specs/changes/ directory found — nothing to migrate.');
      return;
    }
    idsToMigrate.push(
      ...readdirSync(changesDir, { withFileTypes: true })
        .filter(d => d.isDirectory())
        .map(d => d.name),
    );
  } else if (changeId) {
    const specificDir = join(cwd, 'specs', 'changes', changeId);
    if (!existsSync(specificDir)) {
      log.error(`Change not found: specs/changes/${changeId}`);
      process.exit(1);
    }
    idsToMigrate.push(changeId);
  } else {
    log.error('Usage: cdd-kit migrate <change-id>  |  cdd-kit migrate --all  [--dry-run] [--no-backup]');
    process.exit(1);
  }

  if (idsToMigrate.length === 0) {
    log.info('No changes found to migrate.');
    return;
  }

  if (dryRun) {
    log.info('Dry run — no files will be written.');
    log.blank();
  }

  const sessionStamp = new Date().toISOString().replace(/[:.]/g, '-');
  let migratedCount = 0;
  let upToDateCount = 0;
  const backupRoot = join(cwd, '.cdd', 'migrate-backup', sessionStamp);

  for (const id of idsToMigrate) {
    const changeDir = join(cwd, 'specs', 'changes', id);
    if (!existsSync(changeDir)) {
      log.warn(`  ${id}: directory not found — skipping`);
      continue;
    }

    const { result, pending, deletes } = migrateOne(id, changeDir, enableContextGovernance);
    const { changed, warnings } = result;

    if (changed.length === 0) {
      log.info(`  ${id}: already up to date`);
      upToDateCount++;
      for (const w of warnings) log.warn(`  ${id}: ${w}`);
      continue;
    }

    if (!dryRun) {
      try {
        if (!noBackup) backupChangeDir(cwd, id, sessionStamp);
        commitWritesAtomically(pending, deletes);
      } catch (err) {
        log.error(`  ${id}: migration failed — ${(err as Error).message}`);
        if (!noBackup) {
          log.error(`  ${id}: restore from .cdd/migrate-backup/${sessionStamp}/${id}/`);
        }
        process.exit(1);
      }
    }

    log.ok(`  ${id}: migrated`);
    for (const c of changed) log.info(`    + ${c}`);
    migratedCount++;
    for (const w of warnings) log.warn(`  ${id}: ${w}`);
  }

  log.blank();
  if (dryRun) {
    log.info(`Dry run complete: ${migratedCount} change(s) would be updated, ${upToDateCount} already up to date.`);
  } else {
    log.ok(`Migration complete: ${migratedCount} updated, ${upToDateCount} already up to date.`);
    if (migratedCount > 0 && !noBackup) {
      log.info(`Backup: ${backupRoot}`);
      log.info('Next: git add specs/changes/ && git commit -m "chore: migrate changes to YAML format"');
      log.info('When stable, remove backup: rm -rf .cdd/migrate-backup/');
    }
  }
}
