import { join, relative } from 'path';
import { createHash } from 'crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { ASSET } from '../utils/paths.js';
import { copyFile, ensureDir } from '../utils/copy.js';
import { log } from '../utils/logger.js';
import { contextScan } from './context-scan.js';

export interface NewChangeOptions {
  all: boolean;
  force: boolean;
  dependsOn?: string;
  skipScan?: boolean;
}

// Hash uses line-ending normalization — see src/utils/digest.ts for rationale.
import { sha256OfFileNormalized as sha256OfFile } from '../utils/digest.js';

function inputsDigest(paths: string[], cwd: string): string {
  // Repo-relative for portability — must match context-scan.ts and doctor.ts.
  const combined = paths.slice().sort()
    .map(p => {
      const rel = relative(cwd, p).replace(/\\/g, '/');
      return `${rel}:${sha256OfFile(p)}`;
    })
    .join('\n');
  return createHash('sha256').update(combined).digest('hex');
}

function findContractFiles(dir: string, found: string[] = []): string[] {
  if (!existsSync(dir)) return found;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) findContractFiles(fullPath, found);
    else if (entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'INDEX.md' && entry.name !== 'CHANGELOG.md') {
      found.push(fullPath);
    }
  }
  return found;
}

function readIndexDigest(filePath: string): string | null {
  if (!existsSync(filePath)) return null;
  const m = readFileSync(filePath, 'utf8').match(/^inputs-digest:\s*([a-f0-9]+)/m);
  return m ? m[1] : null;
}

async function ensureFreshContextIndexes(cwd: string): Promise<void> {
  const projectMap = join(cwd, 'specs', 'context', 'project-map.md');
  const contractsIndex = join(cwd, 'specs', 'context', 'contracts-index.md');
  const policyPath = join(cwd, '.cdd', 'context-policy.json');

  const policyInputs = [policyPath].filter(existsSync);
  const contractFiles = findContractFiles(join(cwd, 'contracts'));

  const wantProjectDigest = inputsDigest(policyInputs, cwd);
  const wantContractsDigest = inputsDigest(contractFiles, cwd);

  const haveProjectDigest = readIndexDigest(projectMap);
  const haveContractsDigest = readIndexDigest(contractsIndex);

  const needsScan =
    !existsSync(projectMap) ||
    !existsSync(contractsIndex) ||
    haveProjectDigest !== wantProjectDigest ||
    haveContractsDigest !== wantContractsDigest;

  if (!needsScan) return;

  log.info('context indexes missing or stale — running cdd-kit context-scan…');
  await contextScan();
  log.dim('  (skip with --skip-scan)');
}

// The v2 shape (gate-artifacts.ts `REQUIRED_FILES_V2`). change-classification.md
// folded into tasks.yml frontmatter, and test-plan.md / ci-gates.md into
// implementation-plan.md's `## Test Plan` / `## CI Gates` -- same facts, same
// gate checks, three fewer files of template. v1 change directories keep their
// old shape and their old checks; only new changes are scaffolded this way.
const REQUIRED_TEMPLATES = [
  'change-request.md',
  'implementation-plan.md',
  'tasks.yml',
  // context-manifest.md is NOT scaffolded: it is optional under v2 and nothing
  // enforces the read boundary it declares. It stays available via `--all` for
  // a change that genuinely wants to record one. See REQUIRED_FILES_V2's note.
  // ADR 0010 (acceptance-oracle): every new change gets a placeholder-plus-
  // instructions acceptance.yml, mirroring how tasks.yml/context-manifest.md
  // are scaffolded. Unlike test-evidence.yml (NEVER_SCAFFOLD below, since that
  // is runtime-generated), this placeholder is meant to be copied verbatim and
  // then hand-authored — `enforceAcceptanceOracle` (AC-1) fails it until the
  // human replaces the placeholder case with real ones, so it is never
  // silently skipped.
  'acceptance.yml',
  // ADR 0012 (interaction-design-loop): every new change also gets a
  // placeholder-plus-instructions interaction-design.md, same discipline as
  // acceptance.yml immediately above — `enforceInteractionDesign` fails it
  // (findPlaceholders + no human ## Confirmed) until a human confirms a real
  // design, or marks it `applicability: not-applicable` with a reason.
  'interaction-design.md',
];

// Templates that ship in specs/templates/ as the canonical shape but must never
// be scaffolded into a change directory. test-evidence.yml is generated by
// `cdd-kit test run`; a copied example would masquerade as real passing evidence
// (and could be picked up by later gate enforcement) before any test has run.
// test-evidence.yml is generated by `cdd-kit test run`; a copied example would
// masquerade as real passing evidence before any test has run.
//
// The other three are the v1 shape. They still ship in specs/templates/ so a
// legacy v1 change directory (and `cdd-kit migrate`) can still resolve them, but
// scaffolding them into a new change would recreate exactly what v2 removed.
const NEVER_SCAFFOLD = new Set([
  'test-evidence.yml',
  'change-classification.md',
  'test-plan.md',
  'ci-gates.md',
]);

function listOptional(): string[] {
  try {
    const all = readdirSync(ASSET.specsTemplates).filter((f) => f.endsWith('.md') || f.endsWith('.yml'));
    return all.filter((f) => !REQUIRED_TEMPLATES.includes(f) && !NEVER_SCAFFOLD.has(f));
  } catch {
    return [];
  }
}

const SAFE_NAME = /^[a-z0-9][a-z0-9_-]{0,63}$/i;

function parseDependsOn(raw?: string): string[] {
  if (!raw) return [];
  return raw
    .split(',')
    .map(item => item.trim())
    .filter(Boolean);
}

function applyScaffoldMetadata(tasksPath: string, changeId: string, dependencies: string[]): void {
  if (!existsSync(tasksPath)) return;

  let raw = readFileSync(tasksPath, 'utf8');
  raw = raw.replace(/^change-id:\s*<change-id>\s*$/m, `change-id: ${changeId}`);

  if (dependencies.length > 0) {
    const dependsOn = [
      'depends-on:',
      ...dependencies.map(dep => `  - ${JSON.stringify(dep)}`),
    ].join('\n');
    raw = raw.replace(/^depends-on:\s*\[\]\s*$/m, dependsOn);
  }

  writeFileSync(tasksPath, raw, 'utf8');
}

export async function newChange(name: string, opts: NewChangeOptions): Promise<void> {
  if (!SAFE_NAME.test(name)) {
    log.error(`Invalid change name: "${name}". Use letters, numbers, hyphens, or underscores (max 64 chars).`);
    process.exit(1);
  }
  const dependencies = parseDependsOn(opts.dependsOn);
  for (const dep of dependencies) {
    if (!SAFE_NAME.test(dep)) {
      log.error(`Invalid dependency name: "${dep}". Use letters, numbers, hyphens, or underscores (max 64 chars).`);
      process.exit(1);
    }
  }

  const cwd = process.cwd();
  const changeDir = join(cwd, 'specs', 'changes', name);

  if (existsSync(changeDir)) {
    if (opts.force) {
      log.warn(`Forcing re-scaffold of existing change directory: ${changeDir}`);
      log.warn('Existing files will NOT be deleted; only template files will be overwritten.');
    } else {
      log.warn(`Change directory already exists: ${changeDir}`);
      log.warn('Aborting — remove or rename the directory to re-scaffold.');
      return;
    }
  }

  if (!opts.skipScan) {
    try {
      await ensureFreshContextIndexes(cwd);
    } catch (err) {
      log.warn(`context-scan failed: ${(err as Error).message}; continuing without fresh indexes`);
    }
  }

  log.blank();
  log.info(`Creating change scaffold: specs/changes/${name}`);
  ensureDir(changeDir); // no-op if already exists (recursive: true)

  const templates = opts.all
    ? [...REQUIRED_TEMPLATES, ...listOptional()]
    : [...REQUIRED_TEMPLATES];

  let written = 0;
  for (const tmpl of templates) {
    const src  = join(ASSET.specsTemplates, tmpl);
    const dest = join(changeDir, tmpl);
    if (!existsSync(src)) {
      log.warn(`Template not found, skipping: ${tmpl}`);
      continue;
    }
    copyFile(src, dest, { overwrite: opts.force });
    log.dim(tmpl);
    written += 1;
  }

  const tasksPath = join(changeDir, 'tasks.yml');
  applyScaffoldMetadata(tasksPath, name, dependencies);
  if (dependencies.length > 0) {
    log.dim(`depends-on: ${dependencies.join(', ')}`);
  }

  log.blank();
  log.ok(`${written} template(s) created in specs/changes/${name}`);
  log.blank();
}
