/**
 * `cdd-kit parallel arm` — configure the local git merge drivers the parallel
 * workflow's `.gitattributes` entries rely on (ADR 0009).
 *
 * `.gitattributes` marks the regenerated `.cdd/*` indexes as `merge=ours` and
 * the append-only `contracts/CHANGELOG.md` as `merge=union`. `merge=union` is
 * built into git, but `merge=ours` needs a driver registered in the repo's git
 * config. This command registers it (idempotent) so a parallel merge keeps the
 * current branch's generated index instead of raising a pointless conflict on a
 * file that is meant to be regenerated by `cdd-kit refresh` afterwards.
 *
 * Git config is per-clone, not committed, so every worktree/clone that runs
 * parallel integration must arm once. `cdd-kit setup` runs this for you.
 */
import { spawnSync } from 'child_process';
import { existsSync } from 'fs';
import { join } from 'path';
import { log } from '../utils/logger.js';

export interface ParallelArmOptions {
  json?: boolean;
}

function git(args: string[], cwd: string): { ok: boolean; out: string } {
  const r = spawnSync('git', args, { cwd, encoding: 'utf8' });
  return { ok: r.status === 0, out: (r.stdout ?? '').trim() };
}

export async function parallelArm(opts: ParallelArmOptions): Promise<void> {
  const repoRoot = process.cwd();

  if (!existsSync(join(repoRoot, '.git')) && !git(['rev-parse', '--git-dir'], repoRoot).ok) {
    log.error('Not a git repository — cannot arm merge drivers.');
    process.exit(1);
  }

  const res = git(['config', 'merge.ours.driver', 'true'], repoRoot);
  const armed = res.ok;

  if (opts.json) {
    console.log(JSON.stringify({ 'merge.ours.driver': armed ? 'true' : 'failed' }, null, 2));
    process.exit(armed ? 0 : 1);
  }

  if (armed) {
    log.ok('Armed git merge driver: merge.ours.driver=true');
    log.dim('.cdd/* indexes now resolve to "ours" on merge; regenerate with `cdd-kit refresh`.');
    log.dim('contracts/CHANGELOG.md uses the built-in merge=union driver (no config needed).');
  } else {
    log.error('Failed to set merge.ours.driver. Run `git config merge.ours.driver true` manually.');
    process.exit(1);
  }
}
