import { existsSync, readFileSync } from 'fs';
import { dirname, isAbsolute, join, relative, resolve } from 'path';

/**
 * Maps a non-relative import specifier (e.g. `@/utils/foo`, `~/components/Btn`,
 * or a bare baseUrl-rooted `utils/foo`) to candidate repo-relative base paths
 * (forward-slash, no extension). The caller appends extensions / index files
 * and keeps only candidates that exist in the scanned file set.
 *
 * Returns [] when the specifier matches no alias and no baseUrl rule.
 */
export type AliasResolver = (moduleName: string) => string[];

interface TsCompilerOptions {
  baseUrl?: string;
  paths?: Record<string, string[]>;
}

interface TsConfig {
  extends?: string;
  compilerOptions?: TsCompilerOptions;
}

/**
 * Parse a tsconfig/jsconfig. Most are strict JSON; the ones generated by IDEs
 * are JSONC (line/block comments + trailing commas). Try strict JSON first so
 * valid configs round-trip exactly, then fall back to a tolerant strip. Any
 * failure bubbles up as a throw for the caller to swallow into "no aliases".
 */
function parseJsonc(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch {
    // fall through to tolerant parse
  }
  let s = text.replace(/\/\*[\s\S]*?\*\//g, '');           // block comments
  s = s.replace(/(^|[^:"'])\/\/[^\n]*/g, '$1');            // line comments (skip ://)
  s = s.replace(/,(\s*[}\]])/g, '$1');                     // trailing commas
  return JSON.parse(s);
}

function resolveExtendsTarget(fromFile: string, ext: string): string {
  let target = ext;
  if (!target.endsWith('.json')) target += '.json';
  if (target.startsWith('.') || isAbsolute(target)) {
    return resolve(dirname(fromFile), target);
  }
  // package-style `extends: "@tsconfig/node18/tsconfig.json"` — best-effort.
  return resolve(dirname(fromFile), 'node_modules', target);
}

/** Read a config file, shallow-merging `compilerOptions` from `extends`. */
function readConfigFile(file: string, depth: number): TsConfig | null {
  if (depth > 5 || !existsSync(file)) return null;
  let parsed: TsConfig;
  try {
    parsed = parseJsonc(readFileSync(file, 'utf8')) as TsConfig;
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== 'object') return null;

  if (typeof parsed.extends === 'string') {
    const base = readConfigFile(resolveExtendsTarget(file, parsed.extends), depth + 1);
    if (base) {
      parsed = {
        ...parsed,
        compilerOptions: { ...base.compilerOptions, ...parsed.compilerOptions },
      };
    }
  }
  return parsed;
}

/**
 * Build an {@link AliasResolver} from the project's tsconfig.json / jsconfig.json
 * (`compilerOptions.baseUrl` + `compilerOptions.paths`). Returns null when no
 * config or no alias/baseUrl is declared — the graph builder then treats every
 * non-relative import as third-party, exactly as before.
 */
export function loadPathAliases(root: string): AliasResolver | null {
  const configFile = ['tsconfig.json', 'jsconfig.json']
    .map(n => join(root, n))
    .find(existsSync);
  if (!configFile) return null;

  const cfg = readConfigFile(configFile, 0);
  const co = cfg?.compilerOptions;
  if (!co || (!co.baseUrl && !co.paths)) return null;

  const configDir = dirname(configFile);
  const baseUrlAbs = co.baseUrl ? resolve(configDir, co.baseUrl) : configDir;
  const hasBaseUrl = typeof co.baseUrl === 'string';

  const patterns = Object.entries(co.paths ?? {}).map(([pattern, targets]) => ({
    pattern,
    star: pattern.indexOf('*'),
    targets: Array.isArray(targets) ? targets : [],
  }));

  const toRel = (abs: string): string =>
    relative(root, abs).replace(/\\/g, '/').replace(/^\.\//, '');

  return (moduleName: string): string[] => {
    const out: string[] = [];

    for (const { pattern, star, targets } of patterns) {
      if (star === -1) {
        if (moduleName === pattern) {
          for (const t of targets) out.push(toRel(resolve(baseUrlAbs, t)));
        }
        continue;
      }
      const prefix = pattern.slice(0, star);
      const suffix = pattern.slice(star + 1);
      if (
        moduleName.length >= prefix.length + suffix.length &&
        moduleName.startsWith(prefix) &&
        moduleName.endsWith(suffix)
      ) {
        const captured = moduleName.slice(prefix.length, moduleName.length - suffix.length);
        for (const t of targets) {
          out.push(toRel(resolve(baseUrlAbs, t.includes('*') ? t.replace('*', captured) : t)));
        }
      }
    }

    // Classic baseUrl resolution for bare specifiers (skip scoped npm packages).
    if (hasBaseUrl && !moduleName.startsWith('@')) {
      out.push(toRel(resolve(baseUrlAbs, moduleName)));
    }

    return [...new Set(out)].filter(p => p.length > 0 && !p.startsWith('..'));
  };
}
