/**
 * Schema for `specs/changes/<id>/change.yml` — the machine-readable state index
 * for one tracked change (P2-1, docs/machine-readable-change-design.md).
 *
 * This file is GENERATED by `cdd-kit metadata`, never hand-authored. The schema
 * exists so the generator can validate its own output before writing (a derived
 * file must never ship malformed) and so `metadata --check` / `doctor` have a
 * stable contract to read. It is a DERIVED index: the gate still treats the
 * source markdown/YAML artifacts as the source of truth, so a missing or stale
 * change.yml never fails the gate.
 */
export const changeMetadataSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "https://cdd-kit/schemas/change-metadata.schema.json",
  title: "Change Metadata",
  type: "object",
  additionalProperties: false,
  required: ["change-id", "status", "lane", "artifacts", "context", "dependencies", "generated-from"],
  properties: {
    "change-id": { type: "string", pattern: "^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$" },
    status: { type: "string", minLength: 1 },
    tier: { anyOf: [{ type: "integer", minimum: 0, maximum: 5 }, { type: "null" }] },
    // Workflow lane (design doc): a change.yml only exists for a tracked change.
    lane: { type: "string", enum: ["tracked"] },
    // Engineering lane from change-classification.md `## Lane` (ADR 0006), when declared.
    "classification-lane": { type: "string", enum: ["feature", "bug-fix"] },
    types: {
      type: "object",
      additionalProperties: false,
      properties: {
        primary: { anyOf: [{ type: "string" }, { type: "null" }] },
        secondary: { type: "array", items: { type: "string" } },
      },
    },
    "required-agents": { type: "array", items: { type: "string" } },
    artifacts: {
      type: "object",
      additionalProperties: false,
      required: ["required", "optional"],
      properties: {
        required: { type: "array", items: { type: "string" } },
        optional: { type: "array", items: { type: "string" } },
      },
    },
    context: {
      type: "object",
      additionalProperties: false,
      properties: {
        manifest: { anyOf: [{ type: "string" }, { type: "null" }] },
        "allowed-paths-count": { type: "integer", minimum: 0 },
      },
    },
    dependencies: { type: "array", items: { type: "string" } },
    // Per-source-file digest (`sha256:<hex>`) of the artifacts this index was
    // derived from, for cheap staleness probes.
    "generated-from": { type: "object", additionalProperties: { type: "string" } },
  },
} as const;
