/**
 * Schema for `specs/changes/<id>/trace.yml` — a compact traceability index from
 * acceptance criteria to tests, gates, and evidence (P2-1,
 * docs/machine-readable-change-design.md).
 *
 * GENERATED by `cdd-kit metadata` from existing artifacts (change-classification
 * acceptance criteria, test-plan AC→test mapping, ci-gates required gates,
 * agent-log evidence). Like change.yml it is a DERIVED index: its purpose is to
 * let reviewers and agents avoid rereading long markdown; it is never the source
 * of truth and a missing/stale trace.yml never fails the gate.
 *
 * Evidence is recorded at the top level (not per-criterion) because agent-log
 * artifacts do not currently cite acceptance-criterion ids — linking each
 * evidence pointer to a specific AC would be inference, not derivation. A future
 * enhancement can add per-criterion evidence once agent logs carry AC ids.
 */
export const traceMetadataSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "https://cdd-kit/schemas/trace.schema.json",
  title: "Trace Metadata",
  type: "object",
  additionalProperties: false,
  required: ["change-id", "criteria", "required-gates", "evidence", "generated-from"],
  properties: {
    "change-id": { type: "string", pattern: "^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$" },
    criteria: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "text", "tests", "gates"],
        properties: {
          id: { type: "string", minLength: 1 },
          text: { type: "string" },
          tests: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["family", "path"],
              properties: {
                family: { type: "string" },
                path: { type: "string" },
              },
            },
          },
          gates: { type: "array", items: { type: "string" } },
        },
      },
    },
    "required-gates": { type: "array", items: { type: "string" } },
    evidence: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["agent", "type", "pointer"],
        properties: {
          agent: { type: "string" },
          type: { type: "string" },
          pointer: { type: "string" },
        },
      },
    },
    "generated-from": { type: "object", additionalProperties: { type: "string" } },
  },
} as const;
