- uses: conda-incubator/setup-miniconda@v3
  with:
    environment-file: environment.yml
    activate-environment: "{{conda-env-name}}"
    auto-activate-base: false
- name: Lint + Type + Test
  shell: bash -el {0}
  run: |
    ruff check . || true
    mypy src/ || true
    pytest
