// ADR 0012 §2 provenance-reconciliation resolver: the five citation forms and
// four degradation rules that join `interaction-design.md` information items
// and UI states against `contracts/api/api-contract.md` (+ its ADR 0007
// `openapi.json` projection) and `contracts/data/data-shape-contract.md`. See
// docs/adr/0012-interaction-design-loop.md §2 and
// contracts/ci/ci-gate-contract.md `## Provenance Reconciliation Policy` for
// the binding spec; this module implements it, it does not restate it.
//
// Reuse discipline (do NOT re-derive the ADR 0007 projection):
//  - Field-existence / enum-pin citations resolve against the COMMITTED
//    contracts/api/openapi.json, generated by src/commands/openapi-export.ts.
//    Freshness is checked with that same module's own `--check` comparison
//    (openapiExport({ check: true })) -- never a separate staleness check.
//  - Bare-status / errors-column / implicit-status citations resolve directly
//    against the parsed endpoint table (src/contracts/parser.ts
//    `parseEndpoints`) and do NOT need openapi.json at all (ADR 0012 §2: "do
//    NOT require the projection ... stay checkable when ## Schemas is
//    empty").
//  - `contracts/api/api-contract.md` / `contracts/data/data-shape-contract.md`
//    applicability markers are read with `projectApplicability` (parser.ts) --
//    the SAME read-only reader `cdd-kit doctor` already uses to DISPLAY other
//    contracts' markers. This is not a second pass/fail authority for the ADR
//    0011 marker on `interaction-design.md` itself (that stays applicability.py
//    exclusively, see gate-design.ts); it is this resolver's OWN, ADR-0012-
//    specific consumption of a target contract's marker as data, to produce
//    the "citing a family the project declared it does not have" HARD
//    category (ci-gate-contract.md `## Provenance Reconciliation Policy`).

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { openapiExport } from '../commands/openapi-export.js';
import {
  stripFrontmatter,
  parseEndpoints,
  normalizeApiPath,
  projectApplicability,
  DEFAULT_CONTRACT_PATH,
  parseRow,
  isSeparator,
  type EndpointRow,
  type JsonSchema,
  type ApplicabilityProjection,
} from '../contracts/parser.js';
import { sectionBody, stripHtmlComments } from './markdown-section.js';

const DATA_SHAPE_CONTRACT_PATH = 'contracts/data/data-shape-contract.md';
const CI_GATE_CONTRACT_PATH = 'contracts/ci/ci-gate-contract.md';
const OPENAPI_PATH = 'contracts/api/openapi.json';

/** Regex metacharacters to escape when a cited heading name is spliced into a RegExp. */
const HEADING_META = /[.*+?^${}()|[\]\\]/g;

export interface CitationResult {
  ok: boolean;
  message?: string;
}

export interface StateDiscriminatorInput {
  id: string;
  meaning: string;
  discriminator: string;
}

/**
 * Two UI states that differ in meaning MUST cite distinct discriminators (ADR
 * 0012 §2 state-discriminator strictness, decided HARD at introduction). Pure
 * and synchronous: it groups states by their raw (whitespace-normalized)
 * citation string and flags any citation shared by two-or-more DISTINCT
 * `meaning` values. States sharing both citation and meaning are not flagged
 * (that is the same state recorded twice, not a violation).
 */
export function checkStateDiscriminatorUniqueness(states: StateDiscriminatorInput[]): string[] {
  const byCitation = new Map<string, Map<string, string[]>>();
  for (const st of states) {
    const citation = st.discriminator.trim().replace(/\s+/g, ' ');
    if (!citation) continue;
    const meaning = st.meaning.trim();
    if (!byCitation.has(citation)) byCitation.set(citation, new Map());
    const byMeaning = byCitation.get(citation)!;
    if (!byMeaning.has(meaning)) byMeaning.set(meaning, []);
    byMeaning.get(meaning)!.push(st.id);
  }

  const errors: string[] = [];
  for (const [citation, byMeaning] of byCitation) {
    if (byMeaning.size <= 1) continue;
    const detail = [...byMeaning.entries()]
      .map(([meaning, ids]) => ids.join('/') + ' ("' + meaning + '")')
      .join(' vs ');
    errors.push(
      'Two meaning-distinct states share the identical discriminator "' + citation + '": ' + detail +
      ' — ADR 0012 §2 requires meaning-distinct states to cite distinct discriminators (a distinct HTTP status, ' +
      'or a distinct enum-pinned value); the contract must supply a discriminator that tells them apart before ' +
      'either side freezes.',
    );
  }
  return errors;
}

// ── generic markdown-table parsing (mirrors the shared parseRow/isSeparator
//    convention already used by src/contracts/parser.ts, applied here to the
//    interaction-design.md sections that have no dedicated parser) ──────────

export interface ParsedTable {
  header: string[];
  rows: string[][];
}

/**
 * Generic markdown-table parser (header row + separator row + data rows),
 * exported so gate-design.ts's own doc-structure parsing (Presented
 * Information / User Intents / Controls / States) reuses the identical
 * row-splitting logic rather than re-deriving it.
 */
export function parseTable(sectionText: string): ParsedTable {
  const lines = sectionText.split('\n').map(l => l.trim()).filter(l => l.startsWith('|'));
  if (lines.length < 2) return { header: [], rows: [] };
  const header = parseRow(lines[0]).map(h => h.toLowerCase());
  const rows: string[][] = [];
  for (let i = 1; i < lines.length; i += 1) {
    const cells = parseRow(lines[i]);
    if (isSeparator(cells)) continue;
    if (!cells.some(Boolean)) continue;
    rows.push(cells);
  }
  return { header, rows };
}

/** Look up a cell by (lowercased) column name; '' when the column or cell is absent. */
export function tableCell(table: ParsedTable, row: string[], name: string): string {
  const idx = table.header.indexOf(name);
  return idx === -1 ? '' : (row[idx] ?? '').trim();
}

/** Parse the `## Invalid Data Behavior` table's `condition` column values. */
function parseInvalidDataConditions(body: string): Set<string> {
  const table = parseTable(sectionBody(body, 'Invalid Data Behavior'));
  const out = new Set<string>();
  for (const row of table.rows) {
    const condition = tableCell(table, row, 'condition');
    if (condition) out.add(condition);
  }
  return out;
}

// ── cached loaders (one load per gate run, shared across every citation) ───

interface ApiContractEnv {
  exists: boolean;
  applicability: ApplicabilityProjection;
  endpoints: EndpointRow[];
}

interface DataShapeEnv {
  exists: boolean;
  applicability: ApplicabilityProjection;
  conditions: Set<string>;
}

type OpenapiEnv = { ok: true; doc: Record<string, unknown> } | { ok: false; message: string };

interface CiGateEnv {
  exists: boolean;
  applicability: ApplicabilityProjection;
  body: string;
}

export interface ProvenanceCache {
  api?: ApiContractEnv;
  dataShape?: DataShapeEnv;
  openapi?: OpenapiEnv;
  ciGate?: CiGateEnv;
}

function loadApiContract(cwd: string, cache: ProvenanceCache): ApiContractEnv {
  if (cache.api) return cache.api;
  const p = join(cwd, DEFAULT_CONTRACT_PATH);
  if (!existsSync(p)) {
    cache.api = { exists: false, applicability: { status: 'applicable' }, endpoints: [] };
    return cache.api;
  }
  const raw = readFileSync(p, 'utf8');
  const parsed = stripFrontmatter(raw);
  cache.api = {
    exists: true,
    applicability: projectApplicability(parsed.frontmatter),
    endpoints: parseEndpoints(parsed.body),
  };
  return cache.api;
}

function loadDataShapeContract(cwd: string, cache: ProvenanceCache): DataShapeEnv {
  if (cache.dataShape) return cache.dataShape;
  const p = join(cwd, DATA_SHAPE_CONTRACT_PATH);
  if (!existsSync(p)) {
    cache.dataShape = { exists: false, applicability: { status: 'applicable' }, conditions: new Set() };
    return cache.dataShape;
  }
  const raw = readFileSync(p, 'utf8');
  const parsed = stripFrontmatter(raw);
  cache.dataShape = {
    exists: true,
    applicability: projectApplicability(parsed.frontmatter),
    conditions: parseInvalidDataConditions(parsed.body),
  };
  return cache.dataShape;
}

function loadCiGateContract(cwd: string, cache: ProvenanceCache): CiGateEnv {
  if (cache.ciGate) return cache.ciGate;
  const p = join(cwd, CI_GATE_CONTRACT_PATH);
  if (!existsSync(p)) {
    cache.ciGate = { exists: false, applicability: { status: 'applicable' }, body: '' };
    return cache.ciGate;
  }
  const parsed = stripFrontmatter(readFileSync(p, 'utf8'));
  cache.ciGate = {
    exists: true,
    applicability: projectApplicability(parsed.frontmatter),
    body: stripHtmlComments(parsed.body),
  };
  return cache.ciGate;
}

/**
 * Lazily verify + load the ADR 0007 `contracts/api/openapi.json` projection.
 * Reuses `openapiExport`'s own `--check` comparison (the exact mechanism
 * `cdd-kit openapi export --check` runs in CI) rather than re-deriving a
 * staleness check; only field/enum-pin citations pay this cost, and only once
 * per gate run (cached).
 */
async function loadOpenapi(cwd: string, cache: ProvenanceCache): Promise<OpenapiEnv> {
  if (cache.openapi) return cache.openapi;
  const contractPath = join(cwd, DEFAULT_CONTRACT_PATH);
  const outPath = join(cwd, OPENAPI_PATH);
  const code = await openapiExport({ contract: contractPath, out: outPath, check: true });
  if (code !== 0) {
    cache.openapi = {
      ok: false,
      message:
        OPENAPI_PATH + ' is missing or out of sync with ' + DEFAULT_CONTRACT_PATH + ' — run `cdd-kit openapi ' +
        'export --out ' + OPENAPI_PATH + '` and commit it (ADR 0012 §2 field-existence resolution).',
    };
    return cache.openapi;
  }
  try {
    const doc = JSON.parse(readFileSync(outPath, 'utf8')) as Record<string, unknown>;
    cache.openapi = { ok: true, doc };
  } catch (err) {
    cache.openapi = { ok: false, message: OPENAPI_PATH + ' could not be parsed: ' + (err as Error).message };
  }
  return cache.openapi;
}

function findEndpoint(endpoints: EndpointRow[], method: string, path: string): EndpointRow | undefined {
  const wantPath = normalizeApiPath(path);
  return endpoints.find(ep => ep.method.toLowerCase() === method && normalizeApiPath(ep.path) === wantPath);
}

function findOpenapiOperation(doc: Record<string, unknown>, method: string, path: string): Record<string, unknown> | undefined {
  const key = normalizeApiPath(path);
  const paths = doc.paths as Record<string, Record<string, unknown>> | undefined;
  return paths?.[key]?.[method] as Record<string, unknown> | undefined;
}

function getResponseSchema(doc: Record<string, unknown>, op: Record<string, unknown>, method: string): JsonSchema | undefined {
  const code = method === 'post' ? '201' : '200';
  const responses = op.responses as Record<string, { content?: Record<string, { schema?: JsonSchema }> }> | undefined;
  return responses?.[code]?.content?.['application/json']?.schema;
}

/**
 * JSON Schema `type` is a string OR an array of strings — the nullable-union
 * form `"type": ["object", "null"]` is the standard way to say "this field is
 * an object, or null". A strict `=== 'object'` comparison rejected it, so an
 * envelope-tolerant schema could only be cited one level deep while the
 * byte-identical bare-`"object"` schema allowed full dotted paths (#66).
 */
function typeIncludes(node: JsonSchema | undefined, want: string): boolean {
  const t = node?.type as unknown;
  return t === want || (Array.isArray(t) && t.includes(want));
}

/** Follow `$ref` and descend `array.items` until neither applies (bounded to defend against a cyclic/self-referential schema). */
function deref(doc: Record<string, unknown>, schema: JsonSchema | undefined): JsonSchema | undefined {
  let current = schema;
  const components = (doc.components as { schemas?: Record<string, JsonSchema> } | undefined)?.schemas ?? {};
  for (let i = 0; i < 20 && current; i += 1) {
    if (typeof current.$ref === 'string') {
      const name = (current.$ref as string).replace('#/components/schemas/', '');
      current = components[name];
      continue;
    }
    if (typeIncludes(current, 'array') && current.items) {
      current = current.items as JsonSchema;
      continue;
    }
    break;
  }
  return current;
}

/**
 * Walk a dotted field path off a (possibly $ref/array) root schema,
 * transparently descending `items` at every step (ADR 0012 §2: "array-element
 * fields cited by bare name — the resolver descends items transparently").
 */
function resolveDottedField(
  doc: Record<string, unknown>,
  rootSchema: JsonSchema | undefined,
  segments: string[],
): { ok: true; node: JsonSchema } | { ok: false; message: string } {
  let current = deref(doc, rootSchema);
  for (const seg of segments) {
    const properties = current?.properties as Record<string, JsonSchema> | undefined;
    if (!current || !typeIncludes(current, 'object') || !properties || !(seg in properties)) {
      return { ok: false, message: 'field "' + segments.join('.') + '" not found (no property "' + seg + '" on the resolved response schema)' };
    }
    current = deref(doc, properties[seg]);
  }
  if (!current) {
    return { ok: false, message: 'field "' + segments.join('.') + '" did not resolve to a schema node' };
  }
  return { ok: true, node: current };
}

const CITATION_RE = /^(GET|POST|PUT|PATCH|DELETE)\s+(\S+)\s*(?:→|->)\s*(.+)$/i;
const DATA_SHAPE_RE = /^data-shape:\s*(.+)$/i;
const CI_GATE_RE = /^ci-gate:\s*([\s\S]+)$/i;
const IMPLICIT_STATUS_RE = /^HTTP\s+(\d{3})$/i;
const BARE_STATUS_RE = /^\d{3}$/;
const ENUM_PIN_RE = /^([A-Za-z_][\w.]*)=(.+)$/;
const FIELD_ONLY_RE = /^[A-Za-z_][\w.]*$/;

async function resolveDataShapeCitation(condition: string, cwd: string, cache: ProvenanceCache): Promise<CitationResult> {
  const ds = loadDataShapeContract(cwd, cache);
  if (ds.applicability.status === 'invalid') {
    return { ok: false, message: 'data-shape: ' + condition + ': ' + DATA_SHAPE_CONTRACT_PATH + ' ' + ds.applicability.error };
  }
  if (ds.applicability.status === 'not-applicable') {
    return {
      ok: false,
      message:
        'data-shape: ' + condition + ': ' + DATA_SHAPE_CONTRACT_PATH + ' is marked applicability: not-applicable ' +
        '(' + ds.applicability.reason + ') — cannot cite a condition from a contract family the project declared ' +
        'it does not have (ADR 0012 §2 marker-aware degradation).',
    };
  }
  if (!ds.exists) {
    return { ok: false, message: 'data-shape: ' + condition + ': ' + DATA_SHAPE_CONTRACT_PATH + ' not found' };
  }
  if (!ds.conditions.has(condition)) {
    const known = [...ds.conditions].join(', ') || 'none defined';
    return {
      ok: false,
      message:
        'data-shape: ' + condition + ': no matching row in ' + DATA_SHAPE_CONTRACT_PATH + "'s ## Invalid Data " +
        'Behavior `condition` column (known conditions: ' + known + ')',
    };
  }
  return { ok: true };
}

/**
 * Normalize a section body or a cited substring for comparison: strip the
 * inline-formatting characters `*`, `_`, `` ` `` (so `**no** recorded baseline`
 * matches a citation of `no recorded baseline`), then collapse whitespace runs
 * to one space and trim. Comparison itself stays case-SENSITIVE — this is a
 * quoted fragment, not a loose phrase (ci-gate-contract.md §Sixth citation form).
 */
function normalizeCiGateText(s: string): string {
  return s.replace(/[*_`]/g, '').replace(/\s+/g, ' ').trim();
}

/** Count non-overlapping, case-sensitive occurrences of `needle` in `haystack`. */
function countOccurrences(haystack: string, needle: string): number {
  if (needle === '') return 0;
  let count = 0;
  let from = 0;
  for (;;) {
    const at = haystack.indexOf(needle, from);
    if (at === -1) return count;
    count += 1;
    from = at + needle.length;
  }
}

/**
 * Resolve a cited bare heading NAME to the full heading text of the unique
 * heading line whose text is that name, optionally followed by a single
 * trailing parenthetical (`## Provenance Reconciliation Policy (ADR 0012 §2)` is
 * reachable by the bare name `Provenance Reconciliation Policy`). Matching is
 * case-insensitive and trimmed; the returned text preserves the file's actual
 * casing so `sectionBody` (which matches case-sensitively) re-finds it exactly.
 * Returns every matching heading's full text so the caller can distinguish
 * none / exactly-one / ambiguous.
 */
function resolveHeadingLines(body: string, bareName: string): string[] {
  const escaped = bareName.replace(HEADING_META, '\\$&');
  const re = new RegExp(`^#{1,6} (${escaped}(?: \\([^\\n]*\\))?)[ \\t]*$`, 'gim');
  const out: string[] = [];
  for (let m = re.exec(body); m; m = re.exec(body)) out.push(m[1].trim());
  return out;
}

async function resolveCiGateCitation(
  citation: string,
  headingName: string,
  substring: string,
  cwd: string,
  cache: ProvenanceCache,
): Promise<CitationResult> {
  const env = loadCiGateContract(cwd, cache);
  if (env.applicability.status === 'invalid') {
    return { ok: false, message: 'citation "' + citation + '": ' + CI_GATE_CONTRACT_PATH + ' ' + env.applicability.error };
  }
  if (env.applicability.status === 'not-applicable') {
    return {
      ok: false,
      message:
        'citation "' + citation + '": ' + CI_GATE_CONTRACT_PATH + ' is marked applicability: not-applicable ' +
        '(' + env.applicability.reason + ') — cannot cite a section from a contract family the project declared ' +
        'it does not have (ADR 0012 §2 marker-aware degradation).',
    };
  }
  if (!env.exists) {
    return { ok: false, message: 'citation "' + citation + '": ' + CI_GATE_CONTRACT_PATH + ' not found' };
  }

  const headings = resolveHeadingLines(env.body, headingName);
  if (headings.length === 0) {
    return { ok: false, message: 'citation "' + citation + "\": no heading '" + headingName + "' found in " + CI_GATE_CONTRACT_PATH };
  }
  if (headings.length > 1) {
    return {
      ok: false,
      message:
        'citation "' + citation + "\": heading name '" + headingName + "' is ambiguous in " + CI_GATE_CONTRACT_PATH +
        ' (' + headings.length + ' matching heading lines) — disambiguate it',
    };
  }

  const normBody = normalizeCiGateText(sectionBody(env.body, headings[0]));
  const normSub = normalizeCiGateText(substring);
  const n = countOccurrences(normBody, normSub);
  if (n === 0) {
    return { ok: false, message: 'citation "' + citation + "\": substring not found in section '" + headingName + "' of ci-gate-contract.md" };
  }
  if (n >= 2) {
    return {
      ok: false,
      message:
        'citation "' + citation + "\": citation is ambiguous in section '" + headingName + "' (" + n +
        ' occurrences) — lengthen the quoted substring until it identifies one place',
    };
  }
  return { ok: true };
}

async function resolveEndpointCitation(
  citation: string,
  methodRaw: string,
  pathRaw: string,
  rest: string,
  cwd: string,
  cache: ProvenanceCache,
): Promise<CitationResult> {
  const method = methodRaw.toLowerCase();
  const path = pathRaw.trim();

  const api = loadApiContract(cwd, cache);
  if (api.applicability.status === 'invalid') {
    return { ok: false, message: 'citation "' + citation + '": ' + DEFAULT_CONTRACT_PATH + ' ' + api.applicability.error };
  }
  if (api.applicability.status === 'not-applicable') {
    return {
      ok: false,
      message:
        'citation "' + citation + '": ' + DEFAULT_CONTRACT_PATH + ' is marked applicability: not-applicable ' +
        '(' + api.applicability.reason + ') — cannot cite an endpoint from a contract family the project ' +
        'declared it does not have (ADR 0012 §2 marker-aware degradation).',
    };
  }

  const endpoint = findEndpoint(api.endpoints, method, path);
  if (!endpoint) {
    return {
      ok: false,
      message: 'citation "' + citation + '": no ' + methodRaw.toUpperCase() + ' ' + path + ' endpoint row found in ' + DEFAULT_CONTRACT_PATH,
    };
  }

  const implicitMatch = rest.match(IMPLICIT_STATUS_RE);
  if (implicitMatch) {
    const expected = method === 'post' ? '201' : '200';
    if (implicitMatch[1] !== expected) {
      return {
        ok: false,
        message:
          'citation "' + citation + '": the implicit success status for ' + methodRaw.toUpperCase() + ' is HTTP ' +
          expected + ', not HTTP ' + implicitMatch[1] + ' (ADR 0012 §2 implicit-status citation form)',
      };
    }
    return { ok: true };
  }

  if (BARE_STATUS_RE.test(rest)) {
    const codes: string[] = endpoint.errors.match(/\b[1-5]\d\d\b/g) ?? [];
    if (!codes.includes(rest)) {
      return {
        ok: false,
        message:
          'citation "' + citation + '": status ' + rest + ' is not listed in the `errors` column ("' + endpoint.errors +
          '") of ' + methodRaw.toUpperCase() + ' ' + path + ' in ' + DEFAULT_CONTRACT_PATH,
      };
    }
    return { ok: true };
  }

  const enumPinMatch = rest.match(ENUM_PIN_RE);
  const fieldOnly = !enumPinMatch && FIELD_ONLY_RE.test(rest);
  if (!enumPinMatch && !fieldOnly) {
    return {
      ok: false,
      message: 'citation "' + citation + '": "' + rest + '" after the arrow is not a recognized field, enum-pin, or status form (ADR 0012 §2)',
    };
  }

  // Field-existence / enum-pin resolution requires the fresh openapi.json
  // projection (ADR 0012 §2 degradation rule) — never re-derived here.
  const openapi = await loadOpenapi(cwd, cache);
  if (!openapi.ok) {
    return { ok: false, message: 'citation "' + citation + '": ' + openapi.message };
  }

  const op = findOpenapiOperation(openapi.doc, method, path);
  if (!op) {
    return {
      ok: false,
      message: 'citation "' + citation + '": ' + methodRaw.toUpperCase() + ' ' + path + ' not found in ' + OPENAPI_PATH + ' (regenerate it)',
    };
  }
  if (typeof op['x-cdd-response-contract'] === 'string') {
    return {
      ok: false,
      message:
        'citation "' + citation + '": ' + methodRaw.toUpperCase() + ' ' + path + "'s response schema cell (\"" +
        op['x-cdd-response-contract'] + '") is unresolved prose with no matching ## Schemas entry — define a bare ' +
        'schema name and re-run `cdd-kit openapi export` before citing a field on it (ADR 0012 §2).',
    };
  }

  const schema = getResponseSchema(openapi.doc, op, method);
  if (!schema) {
    return { ok: false, message: 'citation "' + citation + '": ' + methodRaw.toUpperCase() + ' ' + path + ' has no resolved response schema to verify a field against' };
  }

  const fieldPath = enumPinMatch ? enumPinMatch[1] : rest;
  const resolved = resolveDottedField(openapi.doc, schema, fieldPath.split('.'));
  if (!resolved.ok) {
    return { ok: false, message: 'citation "' + citation + '": ' + resolved.message };
  }

  if (enumPinMatch) {
    const member = enumPinMatch[2].trim();
    const enumValues = Array.isArray(resolved.node.enum) ? (resolved.node.enum as unknown[]) : null;
    if (!enumValues) {
      return { ok: false, message: 'citation "' + citation + '": field "' + fieldPath + '" has no enum(...) list to pin a member against' };
    }
    if (!enumValues.includes(member)) {
      return {
        ok: false,
        message: 'citation "' + citation + '": "' + member + '" is not a member of ' + fieldPath + "'s enum(" + enumValues.join(', ') + ') list',
      };
    }
  }

  return { ok: true };
}

/**
 * Resolve one ADR 0012 §2 citation string against the contracts. Exposed as a
 * standalone async function (fresh, unshared cache per call) so unit tests can
 * exercise each citation form / degradation rule directly;
 * `reconcileProvenance` below shares one cache across a whole document so a
 * single gate run pays the openapi.json check cost at most once.
 */
export async function resolveCitation(citation: string, cwd: string, cache: ProvenanceCache = {}): Promise<CitationResult> {
  const trimmed = citation.trim();

  const dataShapeMatch = trimmed.match(DATA_SHAPE_RE);
  if (dataShapeMatch) {
    return resolveDataShapeCitation(dataShapeMatch[1].trim(), cwd, cache);
  }

  // Sixth citation form (ci-gate: <heading> :: <exact substring>) — a CLI / gate
  // / hook surface anchor into contracts/ci/ci-gate-contract.md. Matched before
  // the endpoint form because its `ci-gate:` prefix is unambiguous and the
  // endpoint regex would otherwise reject it with a generic message.
  const ciGateMatch = trimmed.match(CI_GATE_RE);
  if (ciGateMatch) {
    const rest = ciGateMatch[1];
    const sep = rest.indexOf('::');
    if (sep === -1) {
      return {
        ok: false,
        message: 'citation "' + citation + '": malformed ci-gate citation — expected `ci-gate: <heading> :: <substring>`',
      };
    }
    return resolveCiGateCitation(citation, rest.slice(0, sep).trim(), rest.slice(sep + 2).trim(), cwd, cache);
  }

  const epMatch = trimmed.match(CITATION_RE);
  if (!epMatch) {
    return {
      ok: false,
      message:
        'citation "' + citation + '" does not match any of the ADR 0012 §2 citation forms (endpoint+field, ' +
        'enum-pin, errors-status, implicit-status, or `data-shape: <condition>`)',
    };
  }

  const methodRaw = epMatch[1];
  const pathRaw = epMatch[2];
  const restRaw = epMatch[3];
  return resolveEndpointCitation(citation, methodRaw, pathRaw, restRaw.trim(), cwd, cache);
}

export interface InfoItemInput {
  item: string;
  provenance: string;
}

/**
 * Reconcile every Presented Information item + UI state's provenance citation
 * against the contracts, plus the state-discriminator uniqueness rule.
 * Returns HARD failure messages only (ADR 0012 §2 has no advisory findings at
 * this per-change layer — the reverse/over-fetch advisory is a separate,
 * corpus-wide `cdd-kit doctor` report, never computed here).
 */
export async function reconcileProvenance(
  cwd: string,
  infoItems: InfoItemInput[],
  states: StateDiscriminatorInput[],
): Promise<string[]> {
  const cache: ProvenanceCache = {};
  const errors: string[] = [];

  for (const info of infoItems) {
    if (!info.provenance) {
      errors.push(
        'Presented Information "' + info.item + '" has no provenance citation — every information item must ' +
        'name its supplier (ADR 0012 §2).',
      );
      continue;
    }
    const r = await resolveCitation(info.provenance, cwd, cache);
    if (!r.ok) errors.push('Presented Information "' + info.item + '": ' + r.message);
  }

  for (const st of states) {
    if (!st.discriminator) {
      errors.push('State "' + st.id + '" has no discriminator citation — every UI state must name its supplier (ADR 0012 §2).');
      continue;
    }
    const r = await resolveCitation(st.discriminator, cwd, cache);
    if (!r.ok) errors.push('State "' + st.id + '": ' + r.message);
  }

  errors.push(...checkStateDiscriminatorUniqueness(states));

  return errors;
}
