import { describe, it, beforeEach, afterEach, expect } from 'vitest';
import { mkdirSync, writeFileSync, readFileSync, existsSync, appendFileSync } from 'fs';
import { join } from 'path';
import yaml from 'js-yaml';
import { runCli, makeTempDir, cleanupDir } from '../helpers.js';

/**
 * CLI tests for `cdd-kit metadata` (P2-1): generation, --check staleness,
 * --json shape, --all, and exit-code semantics. The field-by-field derivation
 * is covered by the pure-builder tests in test/commands/metadata-build.test.ts.
 */

let tmpRepo: string;
let tmpHome: string;

function changeDir(id: string): string {
  return join(tmpRepo, 'specs', 'changes', id);
}

function scaffold(id: string, status = 'in-progress'): void {
  const dir = changeDir(id);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'tasks.yml'),
    `change-id: ${id}\nstatus: ${status}\ntier: 1\ntasks: []\n`);
  writeFileSync(join(dir, 'change-classification.md'), [
    '# Change Classification',
    '## Change Types',
    '- primary: bug-fix',
    '## Inferred Acceptance Criteria',
    '- AC-1: It works.',
    '',
  ].join('\n'));
  writeFileSync(join(dir, 'test-plan.md'), [
    '# Test Plan',
    '## Acceptance Criteria → Test Mapping',
    '| criterion id | test family | test file path | tier |',
    '|---|---|---|---|',
    '| AC-1 | unit | tests/x.test.ts | 1 |',
    '',
  ].join('\n'));
}

beforeEach(() => {
  tmpRepo = makeTempDir('cdd-metadata-cli-repo-');
  tmpHome = makeTempDir('cdd-metadata-cli-home-');
});

afterEach(() => {
  cleanupDir(tmpRepo);
  cleanupDir(tmpHome);
});

describe('cdd-kit metadata', () => {
  it('generates schema-shaped change.yml + trace.yml with a generated-by header', () => {
    scaffold('feat-a');
    const r = runCli(['metadata', 'feat-a'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const changePath = join(changeDir('feat-a'), 'change.yml');
    const tracePath = join(changeDir('feat-a'), 'trace.yml');
    expect(existsSync(changePath)).toBe(true);
    expect(existsSync(tracePath)).toBe(true);

    const changeRaw = readFileSync(changePath, 'utf8');
    expect(changeRaw).toMatch(/^# Generated by `cdd-kit metadata`/);
    const change = yaml.load(changeRaw) as Record<string, unknown>;
    expect(change['change-id']).toBe('feat-a');
    expect(change.lane).toBe('tracked');
    expect(change.tier).toBe(1);

    const trace = yaml.load(readFileSync(tracePath, 'utf8')) as { criteria: Array<{ id: string; tests: unknown[] }> };
    expect(trace.criteria[0].id).toBe('AC-1');
    expect(trace.criteria[0].tests).toEqual([{ family: 'unit', path: 'tests/x.test.ts' }]);
  });

  it('--check exits 0 when metadata is up to date and 1 once a source changes', () => {
    scaffold('feat-b');
    runCli(['metadata', 'feat-b'], { cwd: tmpRepo, home: tmpHome });

    const fresh = runCli(['metadata', 'feat-b', '--check'], { cwd: tmpRepo, home: tmpHome });
    expect(fresh.status).toBe(0);
    expect(fresh.stdout).toMatch(/up to date/);

    // Touch a source that only feeds trace.yml → only trace.yml goes stale.
    appendFileSync(join(changeDir('feat-b'), 'test-plan.md'),
      '| AC-1 | integration | tests/y.test.ts | 1 |\n');
    const stale = runCli(['metadata', 'feat-b', '--check'], { cwd: tmpRepo, home: tmpHome });
    expect(stale.status).toBe(1);
    expect(stale.stdout).toMatch(/stale metadata \(trace\.yml\)/);
  });

  it('--json reports stale files and exits 1', () => {
    scaffold('feat-c');
    const r = runCli(['metadata', 'feat-c', '--check', '--json'], { cwd: tmpRepo, home: tmpHome });
    // Nothing generated yet → both files stale.
    expect(r.status).toBe(1);
    const parsed = JSON.parse(r.stdout) as { results: Array<{ 'change-id': string; stale: string[] }> };
    expect(parsed.results[0]['change-id']).toBe('feat-c');
    expect(parsed.results[0].stale.sort()).toEqual(['change.yml', 'trace.yml']);
  });

  it('exits 1 with a clear error for an unknown change id', () => {
    const r = runCli(['metadata', 'does-not-exist'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status).toBe(1);
    expect(r.stderr + r.stdout).toMatch(/change not found/);
  });

  it('requires a change id when --all is not given', () => {
    const r = runCli(['metadata'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status).toBe(1);
    expect(r.stderr + r.stdout).toMatch(/requires a <change-id>/);
  });

  it('--all processes only in-progress changes', () => {
    scaffold('active-1', 'in-progress');
    scaffold('done-1', 'completed');
    const r = runCli(['metadata', '--all'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);
    expect(existsSync(join(changeDir('active-1'), 'change.yml'))).toBe(true);
    // A completed change is not active → not processed.
    expect(existsSync(join(changeDir('done-1'), 'change.yml'))).toBe(false);
  });
});
