import { describe, it, beforeEach, afterEach, expect } from 'vitest';
import { existsSync, mkdirSync, readdirSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import yaml from 'js-yaml';
import { runCli, makeTempDir, cleanupDir } from '../helpers.js';

// The v2 scaffold set. change-classification.md folded into tasks.yml
// frontmatter; test-plan.md and ci-gates.md into implementation-plan.md.
const REQUIRED_TEMPLATES = [
  'change-request.md',
  'implementation-plan.md',
  'tasks.yml',
  'context-manifest.md',
  'acceptance.yml',
  'interaction-design.md',
];

describe('cdd-kit new', () => {
  let tmpRepo: string;
  let tmpHome: string;

  beforeEach(() => {
    tmpRepo = makeTempDir('cdd-new-repo-');
    tmpHome = makeTempDir('cdd-new-home-');
    // Each test needs a local-only init first
    const r = runCli(['init', '--local-only'], { cwd: tmpRepo, home: tmpHome });
    if (r.status !== 0) {
      throw new Error(`Setup init failed: ${r.stderr}`);
    }
  });

  afterEach(() => {
    cleanupDir(tmpRepo);
    cleanupDir(tmpHome);
  });

  it('new feat-001 creates all required templates and marks context governance v2', () => {
    const r = runCli(['new', 'feat-001'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const changeDir = join(tmpRepo, 'specs', 'changes', 'feat-001');
    expect(existsSync(changeDir), 'change dir missing').toBe(true);

    for (const tmpl of REQUIRED_TEMPLATES) {
      expect(existsSync(join(changeDir, tmpl)), `${tmpl} missing`).toBe(true);
    }

    const raw = readFileSync(join(changeDir, 'tasks.yml'), 'utf8');
    const data = yaml.load(raw) as Record<string, unknown>;
    expect(data['change-id']).toBe('feat-001');
    expect(data['context-governance']).toBe('v2');

    // v2 folded three files away. Scaffolding them again would recreate exactly
    // what it removed, so their absence is the assertion, not an omission.
    for (const gone of ['change-classification.md', 'test-plan.md', 'ci-gates.md']) {
      expect(existsSync(join(changeDir, gone)), `${gone} should not be scaffolded under v2`).toBe(false);
    }
    // ...and the facts they carried are still demanded, in their new home.
    expect(data).toHaveProperty('classification');
  });

  it('new uses bundled package templates, not stale project specs/templates', () => {
    writeFileSync(
      join(tmpRepo, 'specs', 'templates', 'tasks.yml'),
      [
        'change-id: stale-project-template',
        'status: in-progress',
        'tasks: []',
        '',
      ].join('\n'),
      'utf8',
    );

    const r = runCli(['new', 'feat-bundled-template'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const raw = readFileSync(join(tmpRepo, 'specs', 'changes', 'feat-bundled-template', 'tasks.yml'), 'utf8');
    const data = yaml.load(raw) as Record<string, unknown>;
    expect(data['change-id']).toBe('feat-bundled-template');
    expect(data['context-governance']).toBe('v2');
    expect(Array.isArray(data.tasks)).toBe(true);
    expect(data.tasks as unknown[]).toHaveLength(30);
    expect(raw).not.toContain('stale-project-template');
  });

  it('new feat-002 --all creates required + at least 1 optional template', () => {
    const r = runCli(['new', 'feat-002', '--all'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const changeDir = join(tmpRepo, 'specs', 'changes', 'feat-002');
    const files = readdirSync(changeDir).filter((f) => f.endsWith('.md') || f.endsWith('.yml'));
    // Must have all required
    for (const tmpl of REQUIRED_TEMPLATES) {
      expect(files).toContain(tmpl);
    }
    // Must have at least 1 optional (more than just required)
    expect(files.length).toBeGreaterThan(REQUIRED_TEMPLATES.length);
    // test-evidence.yml is generated by `cdd-kit test run`, never scaffolded as a
    // copied example (it would masquerade as real passing evidence), so even --all
    // must not write it into the change directory.
    expect(files).not.toContain('test-evidence.yml');
  });

  it('new feat-oracle scaffolds a placeholder-plus-instructions acceptance.yml (ADR 0010)', () => {
    const r = runCli(['new', 'feat-oracle'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const oraclePath = join(tmpRepo, 'specs', 'changes', 'feat-oracle', 'acceptance.yml');
    expect(existsSync(oraclePath)).toBe(true);

    const raw = readFileSync(oraclePath, 'utf8');
    const data = yaml.load(raw) as Record<string, unknown>;
    expect(data['oracle-version']).toBe('0.1.0');
    expect(data['authored-by']).toBe('human');
    // The scaffold is intentionally all-placeholder — enforceAcceptanceOracle
    // (AC-1) must reject it until a human replaces the case with real values.
    expect(raw).toMatch(/<case-id>/);
  });

  it('new feat-design scaffolds a placeholder-plus-instructions interaction-design.md (ADR 0012)', () => {
    const r = runCli(['new', 'feat-design'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const designPath = join(tmpRepo, 'specs', 'changes', 'feat-design', 'interaction-design.md');
    expect(existsSync(designPath)).toBe(true);

    const raw = readFileSync(designPath, 'utf8');
    // The scaffold is intentionally all-placeholder — enforceInteractionDesign
    // must reject it (findPlaceholders + no human ## Confirmed) until a human
    // confirms a real design, mirroring the acceptance.yml scaffold above.
    expect(raw).toMatch(/<id>/);
    expect(raw).toMatch(/<date>/);
    expect(raw).toMatch(/## Confirmed/);
    expect(raw).toMatch(/## Open Decisions/);
  });

  it('new "bad name" exits non-zero with "Invalid" in stderr', () => {
    const r = runCli(['new', 'bad name'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status).not.toBe(0);
    expect(r.stderr).toMatch(/invalid/i);
  });

  it('new feat-003 twice does not error and preserves first run content', () => {
    // First run
    const r1 = runCli(['new', 'feat-003'], { cwd: tmpRepo, home: tmpHome });
    expect(r1.status, `first run stderr: ${r1.stderr}`).toBe(0);

    const changeDir = join(tmpRepo, 'specs', 'changes', 'feat-003');
    const filesBefore = readdirSync(changeDir).slice().sort();

    // Second run (no --force)
    const r2 = runCli(['new', 'feat-003'], { cwd: tmpRepo, home: tmpHome });
    // Should not error (exits 0 with abort message)
    expect(r2.status, `second run stderr: ${r2.stderr}`).toBe(0);
    // The abort message should appear
    expect(r2.stdout + r2.stderr).toMatch(/abort|already exist/i);

    // Files from first run are preserved
    const filesAfter = readdirSync(changeDir).slice().sort();
    expect(filesAfter).toEqual(filesBefore);
  });

  it('new feat-004 --force overwrites change-request.md', () => {
    // First run
    runCli(['new', 'feat-004'], { cwd: tmpRepo, home: tmpHome });

    const crPath = join(tmpRepo, 'specs', 'changes', 'feat-004', 'change-request.md');
    const originalContent = readFileSync(crPath, 'utf8');

    // User modifies the file
    writeFileSync(crPath, 'MY CUSTOM CONTENT THAT SHOULD BE REPLACED');

    // Run with --force
    const r = runCli(['new', 'feat-004', '--force'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    // File should be restored to template content
    const afterContent = readFileSync(crPath, 'utf8');
    expect(afterContent).toBe(originalContent);
    expect(afterContent).not.toContain('MY CUSTOM CONTENT THAT SHOULD BE REPLACED');
  });

  it('new feat-005 --depends-on records upstream atomic dependencies', () => {
    const r = runCli(['new', 'feat-005', '--depends-on', 'db-schema,api-contract'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    const raw = readFileSync(join(tmpRepo, 'specs', 'changes', 'feat-005', 'tasks.yml'), 'utf8');
    const data = yaml.load(raw) as Record<string, unknown>;
    expect(data['depends-on']).toEqual(['db-schema', 'api-contract']);
  });

  it('new with no name argument exits non-zero', () => {
    const r = runCli(['new'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status).not.toBe(0);
  });

  // ─────────────────────────────────────────────────────────────────────────
  // PR-3 #2: cdd-kit new auto-runs context-scan when indexes are stale/missing
  // ─────────────────────────────────────────────────────────────────────────

  it('PR3-2.1: auto-runs context-scan when specs/context indexes are missing', () => {
    // Indexes do not exist after init+local-only.
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(false);

    const r = runCli(['new', 'feat-auto-scan'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    // After new, indexes must exist.
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(true);
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'contracts-index.md'))).toBe(true);
    // And the message says it scanned.
    expect(r.stdout + r.stderr).toMatch(/context indexes missing or stale.*context-scan/i);
  });

  it('PR3-2.2: --skip-scan disables auto-scan', () => {
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(false);

    const r = runCli(['new', 'feat-skip-scan', '--skip-scan'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);

    // Indexes still don't exist.
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(false);
    expect(r.stdout + r.stderr).not.toMatch(/context indexes missing or stale/i);
  });

  it('PR3-2.3: skips auto-scan when indexes are fresh', () => {
    // Run scan once, indexes are fresh.
    runCli(['context-scan'], { cwd: tmpRepo, home: tmpHome });
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(true);

    const r = runCli(['new', 'feat-fresh'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);
    // Should NOT say "missing or stale"
    expect(r.stdout + r.stderr).not.toMatch(/context indexes missing or stale/i);
  });

  it('PR3-2.4: existing change without --force does not mutate specs/context before aborting', () => {
    const existingDir = join(tmpRepo, 'specs', 'changes', 'feat-existing');
    mkdirSync(existingDir, { recursive: true });
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(false);

    const r = runCli(['new', 'feat-existing'], { cwd: tmpRepo, home: tmpHome });
    expect(r.status, `stderr: ${r.stderr}`).toBe(0);
    expect(r.stdout + r.stderr).toMatch(/change directory already exists/i);
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'project-map.md'))).toBe(false);
    expect(existsSync(join(tmpRepo, 'specs', 'context', 'contracts-index.md'))).toBe(false);
  });
});
