import { existsSync, readFileSync, statSync } from 'fs';
import { join } from 'path';
import { walkRepo } from './include-exclude.js';
import { loadCodeMapConfig } from './config.js';
import { computeSourcesDigest } from '../commands/code-map.js';

export interface FreshnessResult {
  status: 'ok' | 'stale' | 'missing-with-sources' | 'missing-greenfield' | 'config-error';
  staleFiles: string[];   // up to 5
  staleCount: number;     // total
  mapPath: string;
  /** Populated only when status === 'config-error'. */
  configError?: string;
  /**
   * True when the `ok` verdict came from the expensive content-digest path
   * (mtime claimed stale but the hash matched) rather than the cheap mtime
   * check. The query path uses this to repair the map's mtime so subsequent
   * queries skip the full-tree digest recompute. See P1-8.
   */
  verifiedByDigest?: boolean;
}

/**
 * Check whether .cdd/code-map.yml is fresh relative to source files.
 *
 * Uses the resolved code-map config (built-in defaults, optionally replaced by
 * .cdd/code-map-config.yml). Caller-supplied include/exclude are appended on
 * top — passed through for callers (e.g. tests) that want to narrow further.
 *
 * If the user's `.cdd/code-map-config.yml` is malformed, this returns
 * `status: 'config-error'`. Callers (gate, doctor) MUST surface that to the
 * user — silently degrading to "no files matched" was the 2.0.6 audit's RISK
 * #5 finding.
 */
export function checkCodeMapFreshness(
  cwd: string,
  mapRel: string = '.cdd/code-map.yml',
  include?: string[],
  exclude?: string[],
): FreshnessResult {
  const mapPath = join(cwd, mapRel);

  let cfg;
  try {
    cfg = loadCodeMapConfig(cwd);
  } catch (err) {
    return {
      status: 'config-error',
      staleFiles: [],
      staleCount: 0,
      mapPath,
      configError: (err as Error).message,
    };
  }
  const includeFinal = [...cfg.include, ...(include ?? [])];
  const excludeFinal = [...cfg.exclude, ...(exclude ?? [])];

  const sourceFiles = walkRepo(cwd, { include: includeFinal, exclude: excludeFinal });

  if (!existsSync(mapPath)) {
    if (sourceFiles.length === 0) {
      return { status: 'missing-greenfield', staleFiles: [], staleCount: 0, mapPath };
    }
    return { status: 'missing-with-sources', staleFiles: [], staleCount: 0, mapPath };
  }

  const mapMtime = statSync(mapPath).mtimeMs;

  // Step 1 — fast mtime check. If everything looks fresh by mtime, we're done.
  const staleAll: string[] = [];
  for (const absPath of sourceFiles) {
    try {
      const mtime = statSync(absPath).mtimeMs;
      if (mtime > mapMtime) {
        const rel = absPath.replace(/\\/g, '/').replace(cwd.replace(/\\/g, '/') + '/', '');
        staleAll.push(rel);
      }
    } catch {
      // file vanished between walk and stat — ignore
    }
  }

  if (staleAll.length === 0) {
    return { status: 'ok', staleFiles: [], staleCount: 0, mapPath };
  }

  // Step 2 — mtime says stale. mtime is unreliable across `git clone` (all
  // files get the clone time, but in some unpredictable order) so a "stale"
  // verdict from mtime alone produces frequent false positives. Verify by
  // hash: re-compute the sources digest and compare to the value stamped in
  // the map header. Maps generated by cdd-kit < 2.0.10 lack this header line;
  // for those, fall back to the mtime verdict (legacy behaviour).
  const declaredDigest = readSourcesDigest(mapPath);
  if (declaredDigest !== null) {
    const actualDigest = computeSourcesDigest(sourceFiles, cwd);
    if (actualDigest === declaredDigest) {
      return { status: 'ok', staleFiles: [], staleCount: 0, mapPath, verifiedByDigest: true };
    }
  }

  return {
    status: 'stale',
    staleFiles: staleAll.slice(0, 5),
    staleCount: staleAll.length,
    mapPath,
  };
}

/**
 * Extract `# sources-digest: <hex>` from the code-map header, if present.
 * Returns null when the line is absent (legacy maps).
 */
function readSourcesDigest(mapPath: string): string | null {
  try {
    const head = readFileSync(mapPath, 'utf8').slice(0, 2048);
    const m = head.match(/^# sources-digest:\s*([a-f0-9]+)/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}
